// GENERATED by scripts/build-public-law-registry.ts from registry_v06_1.jsonl — do not edit.
// Federal court directory (client-safe, ~40 KB): official URLs, practice pages, JPML active-MDL metadata.
// Registry records: 9348; verified through 2026-08-19.

export const COURT_DIRECTORY_AS_OF = "2026-08-19";

export type CourtPages = Partial<Record<"rules" | "orders" | "judges" | "forms" | "efiling" | "admissions" | "adr", string>>;
export type CourtMdl = { number: string; title: string; pending: number | null; judgeUrl?: string; judge?: string };
export type CourtDirectoryEntry = {
  id: string;
  host: string;
  kind: "district" | "circuit" | "jpml";
  url: string;
  pages: CourtPages;
  /** JPML district report summary (report date in the registry section title). */
  mdl: { active: number; pending: number; judges: string[] } | null;
  mdls: CourtMdl[];
};

export const COURT_DIRECTORY: readonly CourtDirectoryEntry[] = [
 {
  "id": "akd",
  "host": "akd.uscourts.gov",
  "kind": "district",
  "url": "https://www.akd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "almd",
  "host": "almd.uscourts.gov",
  "kind": "district",
  "url": "https://www.almd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "alnd",
  "host": "alnd.uscourts.gov",
  "kind": "district",
  "url": "https://www.alnd.uscourts.gov/",
  "pages": {
   "rules": "https://www.alnd.uscourts.gov/court-info/local-rules-and-orders",
   "orders": "https://www.alnd.uscourts.gov/general-orders-sorted-date-and-title",
   "forms": "https://www.alnd.uscourts.gov/alnd-forms",
   "adr": "https://www.alnd.uscourts.gov/alternative-dispute-resolution-plan",
   "admissions": "https://www.alnd.uscourts.gov/forms/attorney-admission-application-revised-09222025",
   "judges": "https://www.alnd.uscourts.gov/policies-and-procedures"
  },
  "mdl": {
   "active": 1,
   "pending": 22,
   "judges": [
    "Anna M. Manasco"
   ]
  },
  "mdls": []
 },
 {
  "id": "alsd",
  "host": "alsd.uscourts.gov",
  "kind": "district",
  "url": "https://www.alsd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "arwd",
  "host": "arwd.uscourts.gov",
  "kind": "district",
  "url": "https://www.arwd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "azd",
  "host": "azd.uscourts.gov",
  "kind": "district",
  "url": "https://www.azd.uscourts.gov/",
  "pages": {
   "rules": "https://www.azd.uscourts.gov/282255",
   "forms": "https://www.azd.uscourts.gov/form",
   "efiling": "https://www.azd.uscourts.gov/e-filing-procedural-information",
   "adr": "https://www.azd.uscourts.gov/ADR",
   "admissions": "https://www.azd.uscourts.gov/forms/application-and-instructions-arizona-attorneys-gain-admission-practice"
  },
  "mdl": {
   "active": 1,
   "pending": 3734,
   "judges": [
    "David G. Campbell"
   ]
  },
  "mdls": [
   {
    "number": "3081",
    "title": "Bard Implanted Port Catheter Products Liability Litigation",
    "pending": 3734
   }
  ]
 },
 {
  "id": "ca1",
  "host": "ca1.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.ca1.uscourts.gov/",
  "pages": {
   "orders": "https://www.ca1.uscourts.gov/notice-rule-amendments",
   "forms": "https://www.ca1.uscourts.gov/forms-instructions",
   "efiling": "https://www.ca1.uscourts.gov/cmecf",
   "adr": "https://www.ca1.uscourts.gov/mediation",
   "admissions": "https://www.ca1.uscourts.gov/attorney-admissions",
   "judges": "https://www.ca1.uscourts.gov/judges",
   "rules": "https://www.ca1.uscourts.gov/rules-procedures"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ca10",
  "host": "ca10.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.ca10.uscourts.gov/",
  "pages": {
   "efiling": "https://www.ca10.uscourts.gov/cmecf",
   "judges": "https://www.ca10.uscourts.gov/judges",
   "forms": "https://www.ca10.uscourts.gov/forms/all",
   "rules": "https://www.ca10.uscourts.gov/clerk/rules"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ca11",
  "host": "ca11.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.ca11.uscourts.gov/",
  "pages": {
   "judges": "https://www.ca11.uscourts.gov/judges",
   "forms": "https://www.ca11.uscourts.gov/index.php/forms-information",
   "rules": "https://www.ca11.uscourts.gov/rules-procedures"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ca2",
  "host": "ca2.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.ca2.uscourts.gov/",
  "pages": {
   "rules": "https://www.ca2.uscourts.gov/clerk/case_filing/rules/rules_home.html",
   "efiling": "https://www.ca2.uscourts.gov/clerk/case_filing/case_filing_info_nextgen.html",
   "adr": "https://www.ca2.uscourts.gov/clerk/attorneys/attorneys.html",
   "admissions": "https://www.ca2.uscourts.gov/clerk/attorneys/admission_instructions.html",
   "forms": "https://www.ca2.uscourts.gov/clerk/case_filing/forms/forms_home.html"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ca3",
  "host": "ca3.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.ca3.uscourts.gov/",
  "pages": {
   "rules": "https://www.ca3.uscourts.gov/rulesprocedures",
   "orders": "https://www.ca3.uscourts.gov/standing-orders-0",
   "efiling": "https://www.ca3.uscourts.gov/electronic-filing",
   "adr": "https://www.ca3.uscourts.gov/mediation",
   "admissions": "https://www.ca3.uscourts.gov/attorney-admissions",
   "judges": "https://www.ca3.uscourts.gov/judges-biographies",
   "forms": "https://www.ca3.uscourts.gov/allforms"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ca4",
  "host": "ca4.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.ca4.uscourts.gov/",
  "pages": {
   "orders": "https://www.ca4.uscourts.gov/rules-and-procedures/rule-amendments/archived-local-rule-amendments",
   "efiling": "https://www.ca4.uscourts.gov/caseinformationefiling/efiling_cm-ecf",
   "adr": "https://www.ca4.uscourts.gov/mediation",
   "admissions": "https://www.ca4.uscourts.gov/caseinformationefiling/efiling_cm-ecf/training/submit-bar-application",
   "judges": "https://www.ca4.uscourts.gov/judges",
   "forms": "https://www.ca4.uscourts.gov/court-forms-fees",
   "rules": "https://www.ca4.uscourts.gov/LocalRules/LocalRules-TOC.html"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ca5",
  "host": "ca5.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.ca5.uscourts.gov/",
  "pages": {
   "rules": "https://www.ca5.uscourts.gov/rules-procedures",
   "forms": "https://www.ca5.uscourts.gov/forms-fees/forms",
   "efiling": "https://www.ca5.uscourts.gov/electronic-case-filing",
   "admissions": "https://www.ca5.uscourts.gov/bar-admission-membership",
   "judges": "https://www.ca5.uscourts.gov/about-the-court/fifth-circuit-judges"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ca6",
  "host": "ca6.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.ca6.uscourts.gov/",
  "pages": {
   "rules": "https://www.ca6.uscourts.gov/rules-and-procedures",
   "efiling": "https://www.ca6.uscourts.gov/ecf/login-cmecf",
   "adr": "https://www.ca6.uscourts.gov/mediation-contact-information",
   "admissions": "https://www.ca6.uscourts.gov/attorneys",
   "judges": "https://www.ca6.uscourts.gov/judges",
   "forms": "https://www.ca6.uscourts.gov/court-forms"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ca7",
  "host": "ca7.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.ca7.uscourts.gov/",
  "pages": {
   "rules": "https://www.ca7.uscourts.gov/pages/LandingPage.php?page=rules-procedures",
   "forms": "https://www.ca7.uscourts.gov/pages/LandingPage.php?page=forms",
   "efiling": "https://www.ca7.uscourts.gov/pages/LandingPage.php?page=case-information",
   "adr": "https://www.ca7.uscourts.gov/pages/LandingPage.php?page=mediation",
   "admissions": "https://www.ca7.uscourts.gov/pages/LandingPage.php?page=for-attorneys",
   "judges": "https://www.ca7.uscourts.gov/pages/LandingPage.php?page=judges"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ca8",
  "host": "ca8.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.ca8.uscourts.gov/",
  "pages": {
   "rules": "https://www.ca8.uscourts.gov/rules-procedures",
   "adr": "https://www.ca8.uscourts.gov/mediation",
   "admissions": "https://www.ca8.uscourts.gov/attorney-admissions",
   "judges": "https://www.ca8.uscourts.gov/judges",
   "forms": "https://www.ca8.uscourts.gov/all-forms"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ca9",
  "host": "ca9.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.ca9.uscourts.gov/",
  "pages": {
   "rules": "https://www.ca9.uscourts.gov/rules/",
   "adr": "https://www.ca9.uscourts.gov/mediation/",
   "admissions": "https://www.ca9.uscourts.gov/attorneys/",
   "forms": "https://www.ca9.uscourts.gov/filing/forms"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "cacd",
  "host": "cacd.uscourts.gov",
  "kind": "district",
  "url": "https://www.cacd.uscourts.gov/",
  "pages": {
   "forms": "https://www.cacd.uscourts.gov/court-procedures/forms?category=Vendor",
   "efiling": "https://www.cacd.uscourts.gov/e-filing",
   "adr": "https://www.cacd.uscourts.gov/attorneys/adr",
   "admissions": "https://www.cacd.uscourts.gov/attorneys/admissions",
   "judges": "https://www.cacd.uscourts.gov/judges-requirements",
   "rules": "https://www.cacd.uscourts.gov/court-procedures/local-rules",
   "orders": "https://www.cacd.uscourts.gov/court-procedures/general-orders"
  },
  "mdl": {
   "active": 6,
   "pending": 307,
   "judges": [
    "James V. Selna",
    "Andre Birotte, Jr",
    "John A. Kronstadt",
    "George H. Wu",
    "Josephine L. Staton"
   ]
  },
  "mdls": []
 },
 {
  "id": "cadc",
  "host": "cadc.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.cadc.uscourts.gov/",
  "pages": {
   "rules": "https://www.cadc.uscourts.gov/circuit-rules-procedures",
   "orders": "https://www.cadc.uscourts.gov/general-notices",
   "efiling": "https://www.cadc.uscourts.gov/cmecf",
   "adr": "https://www.cadc.uscourts.gov/appellate-mediation-program",
   "admissions": "https://www.cadc.uscourts.gov/attorney-admissions",
   "judges": "https://www.cadc.uscourts.gov/judges",
   "forms": "https://www.cadc.uscourts.gov/forms"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "caed",
  "host": "caed.uscourts.gov",
  "kind": "district",
  "url": "https://www.caed.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "cafc",
  "host": "cafc.uscourts.gov",
  "kind": "circuit",
  "url": "https://www.cafc.uscourts.gov/",
  "pages": {
   "rules": "https://www.cafc.uscourts.gov/home/rules-procedures-forms/federal-local-rules-of-appellate-procedure",
   "orders": "https://www.cafc.uscourts.gov/home/the-court/administrative-orders",
   "efiling": "https://www.cafc.uscourts.gov/home/case-information/electronic-filing-information/electronic-filing-procedures",
   "adr": "https://www.cafc.uscourts.gov/home/case-information/mediation",
   "admissions": "https://www.cafc.uscourts.gov/home/case-information/electronic-filing-information/electronic-filing-registration",
   "judges": "https://www.cafc.uscourts.gov/home/the-court/judges"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "cand",
  "host": "cand.uscourts.gov",
  "kind": "district",
  "url": "https://www.cand.uscourts.gov/",
  "pages": {
   "rules": "https://cand.uscourts.gov/rules-forms-fees/local-rules",
   "forms": "https://cand.uscourts.gov/rules-forms-fees/forms",
   "efiling": "https://cand.uscourts.gov/cases-e-filing/cmecf-information/e-filing-case-documents",
   "admissions": "https://cand.uscourts.gov/attorneys/admission-bar-membership",
   "orders": "https://cand.uscourts.gov/rules-forms-fees/general-orders",
   "adr": "https://cand.uscourts.gov/about-court/court-programs-services/alternative-dispute-resolution-adr/adr-forms",
   "judges": "https://cand.uscourts.gov/judges"
  },
  "mdl": null,
  "mdls": [
   {
    "number": "3084",
    "title": "Uber Technologies, Inc., Passenger Sexual Assault Litigation",
    "pending": 4397
   }
  ]
 },
 {
  "id": "casd",
  "host": "casd.uscourts.gov",
  "kind": "district",
  "url": "https://www.casd.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 4,
   "pending": 524,
   "judges": [
    "Dana M. Sabraw",
    "Gonzalo P. Curiel",
    "Jinsook Ohta",
    "Anthony J. Battaglia"
   ]
  },
  "mdls": []
 },
 {
  "id": "cod",
  "host": "cod.uscourts.gov",
  "kind": "district",
  "url": "https://www.cod.uscourts.gov/Home.aspx",
  "pages": {},
  "mdl": {
   "active": 1,
   "pending": 24,
   "judges": [
    "Philip A. Brimmer"
   ]
  },
  "mdls": []
 },
 {
  "id": "ctd",
  "host": "ctd.uscourts.gov",
  "kind": "district",
  "url": "https://www.ctd.uscourts.gov/ctp",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "dcd",
  "host": "dcd.uscourts.gov",
  "kind": "district",
  "url": "https://www.dcd.uscourts.gov/",
  "pages": {
   "admissions": "https://www.dcd.uscourts.gov/attorney-admissions",
   "judges": "https://www.dcd.uscourts.gov/judges"
  },
  "mdl": {
   "active": 3,
   "pending": 118,
   "judges": [
    "Emmet G. Sullivan",
    "Colleen Kollar-Kotelly",
    "John D. Bates"
   ]
  },
  "mdls": []
 },
 {
  "id": "ded",
  "host": "ded.uscourts.gov",
  "kind": "district",
  "url": "https://www.ded.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 2,
   "pending": 27,
   "judges": [
    "Joshua D. Wolson",
    "Richard G. Andrews"
   ]
  },
  "mdls": []
 },
 {
  "id": "flmd",
  "host": "flmd.uscourts.gov",
  "kind": "district",
  "url": "https://www.flmd.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 1,
   "pending": 36,
   "judges": [
    "Roy B. Dalton, Jr"
   ]
  },
  "mdls": []
 },
 {
  "id": "flnd",
  "host": "flnd.uscourts.gov",
  "kind": "district",
  "url": "https://www.flnd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": [
   {
    "number": "3140",
    "title": "Depo-Provera (Depot Medroxyprogesterone Acetate) Products Liability Litigation",
    "pending": 6294
   }
  ]
 },
 {
  "id": "flsd",
  "host": "flsd.uscourts.gov",
  "kind": "district",
  "url": "https://www.flsd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": [
   {
    "number": "2924",
    "title": "Zantac (Ranitidine) Products Liability Litigation",
    "pending": 847
   }
  ]
 },
 {
  "id": "gamd",
  "host": "gamd.uscourts.gov",
  "kind": "district",
  "url": "https://www.gamd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "gand",
  "host": "gand.uscourts.gov",
  "kind": "district",
  "url": "https://www.gand.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": [
   {
    "number": "2974",
    "title": "Paragard IUD Products Liability Litigation",
    "pending": 4156
   }
  ]
 },
 {
  "id": "gasd",
  "host": "gasd.uscourts.gov",
  "kind": "district",
  "url": "https://www.gasd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "gud",
  "host": "gud.uscourts.gov",
  "kind": "district",
  "url": "https://www.gud.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "hid",
  "host": "hid.uscourts.gov",
  "kind": "district",
  "url": "https://www.hid.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "iand",
  "host": "iand.uscourts.gov",
  "kind": "district",
  "url": "https://www.iand.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "iasd",
  "host": "iasd.uscourts.gov",
  "kind": "district",
  "url": "https://www.iasd.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 1,
   "pending": 0,
   "judges": [
    "Stephen H. Locher"
   ]
  },
  "mdls": []
 },
 {
  "id": "ilcd",
  "host": "ilcd.uscourts.gov",
  "kind": "district",
  "url": "https://www.ilcd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ilnd",
  "host": "ilnd.uscourts.gov",
  "kind": "district",
  "url": "https://www.ilnd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": [
   {
    "number": "3060",
    "title": "Hair Relaxer Marketing, Sales Practices, and Products Liability Litigation",
    "pending": 11779
   }
  ]
 },
 {
  "id": "ilsd",
  "host": "ilsd.uscourts.gov",
  "kind": "district",
  "url": "https://www.ilsd.uscourts.gov/",
  "pages": {
   "rules": "https://www.ilsd.uscourts.gov/court-info/local-rules-and-orders"
  },
  "mdl": {
   "active": 1,
   "pending": 6665,
   "judges": [
    "Nancy J. Rosenstengel"
   ]
  },
  "mdls": []
 },
 {
  "id": "innd",
  "host": "innd.uscourts.gov",
  "kind": "district",
  "url": "https://www.innd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "insd",
  "host": "insd.uscourts.gov",
  "kind": "district",
  "url": "https://www.insd.uscourts.gov/",
  "pages": {
   "rules": "https://www.insd.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.insd.uscourts.gov/forms"
  },
  "mdl": {
   "active": 1,
   "pending": 6537,
   "judges": [
    "Richard L. Young"
   ]
  },
  "mdls": []
 },
 {
  "id": "jpml",
  "host": "jpml.uscourts.gov",
  "kind": "jpml",
  "url": "https://www.jpml.uscourts.gov/",
  "pages": {
   "forms": "https://jpml.uscourts.gov/forms"
  },
  "mdl": null,
  "mdls": [
   {
    "number": "2738",
    "title": "Johnson & Johnson Talcum Powder Products Marketing, Sales Practices and Products Liability Litigation",
    "pending": 68914
   }
  ]
 },
 {
  "id": "ksd",
  "host": "ksd.uscourts.gov",
  "kind": "district",
  "url": "https://www.ksd.uscourts.gov/",
  "pages": {
   "rules": "https://www.ksd.uscourts.gov/court-info/local-rules-and-orders",
   "efiling": "https://www.ksd.uscourts.gov/cmecf"
  },
  "mdl": {
   "active": 1,
   "pending": 36,
   "judges": [
    "Eric F. Melgren"
   ]
  },
  "mdls": []
 },
 {
  "id": "kyed",
  "host": "kyed.uscourts.gov",
  "kind": "district",
  "url": "https://www.kyed.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "kywd",
  "host": "kywd.uscourts.gov",
  "kind": "district",
  "url": "https://www.kywd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "laed",
  "host": "laed.uscourts.gov",
  "kind": "district",
  "url": "https://www.laed.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 3,
   "pending": 278,
   "judges": [
    "Carl J. Barbier",
    "Jane Triche Milazzo"
   ]
  },
  "mdls": []
 },
 {
  "id": "lamd",
  "host": "lamd.uscourts.gov",
  "kind": "district",
  "url": "https://www.lamd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "lawd",
  "host": "lawd.uscourts.gov",
  "kind": "district",
  "url": "https://www.lawd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "mad",
  "host": "mad.uscourts.gov",
  "kind": "district",
  "url": "https://www.mad.uscourts.gov/",
  "pages": {
   "rules": "https://www.mad.uscourts.gov/general/rules-home.htm",
   "adr": "https://www.mad.uscourts.gov/attorneys/pro-bono-mediation.htm",
   "admissions": "https://www.mad.uscourts.gov/attorneys/admission-info.htm",
   "judges": "https://www.mad.uscourts.gov/general/judges.htm"
  },
  "mdl": {
   "active": 6,
   "pending": 2765,
   "judges": [
    "Nathaniel M. Gorton",
    "Indira Talwani",
    "Denise J. Casper",
    "Patti B. Saris",
    "Allison D. Burroughs"
   ]
  },
  "mdls": []
 },
 {
  "id": "mdd",
  "host": "mdd.uscourts.gov",
  "kind": "district",
  "url": "https://www.mdd.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 2,
   "pending": 73,
   "judges": [
    "James K. Bredar",
    "John P. Bailey"
   ]
  },
  "mdls": []
 },
 {
  "id": "med",
  "host": "med.uscourts.gov",
  "kind": "district",
  "url": "https://www.med.uscourts.gov/",
  "pages": {
   "forms": "https://www.med.uscourts.gov/forms"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "mied",
  "host": "mied.uscourts.gov",
  "kind": "district",
  "url": "https://www.mied.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 5,
   "pending": 62,
   "judges": [
    "F. Kay Behm",
    "Matthew F. Leitman",
    "Terrence G. Berg",
    "David M. Lawson",
    "Mark A. Goldsmith"
   ]
  },
  "mdls": []
 },
 {
  "id": "miwd",
  "host": "miwd.uscourts.gov",
  "kind": "district",
  "url": "https://www.miwd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "mnd",
  "host": "mnd.uscourts.gov",
  "kind": "district",
  "url": "https://www.mnd.uscourts.gov/",
  "pages": {
   "rules": "https://www.mnd.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.mnd.uscourts.gov/forms",
   "admissions": "https://www.mnd.uscourts.gov/attorney-admissions",
   "judges": "https://www.mnd.uscourts.gov/judges"
  },
  "mdl": {
   "active": 8,
   "pending": 8772,
   "judges": [
    "Donovan W. Frank",
    "Joan N. Ericksen",
    "John R. Tunheim",
    "Jerry W. Blackwell",
    "Katherine Marie Menendez"
   ]
  },
  "mdls": [
   {
    "number": "2666",
    "title": "Bair Hugger Forced Air Warming Devices Products Liability Litigation",
    "pending": 8407
   }
  ]
 },
 {
  "id": "moed",
  "host": "moed.uscourts.gov",
  "kind": "district",
  "url": "https://www.moed.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 1,
   "pending": 28,
   "judges": [
    "John Andrew Ross"
   ]
  },
  "mdls": []
 },
 {
  "id": "msnd",
  "host": "msnd.uscourts.gov",
  "kind": "district",
  "url": "https://www.msnd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "mssd",
  "host": "mssd.uscourts.gov",
  "kind": "district",
  "url": "https://www.mssd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "mtd",
  "host": "mtd.uscourts.gov",
  "kind": "district",
  "url": "https://www.mtd.uscourts.gov/",
  "pages": {
   "rules": "https://www.mtd.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.mtd.uscourts.gov/forms",
   "admissions": "https://www.mtd.uscourts.gov/attorney-admissions",
   "judges": "https://www.mtd.uscourts.gov/judges"
  },
  "mdl": {
   "active": 1,
   "pending": 71,
   "judges": [
    "Brian Morris"
   ]
  },
  "mdls": []
 },
 {
  "id": "nced",
  "host": "nced.uscourts.gov",
  "kind": "district",
  "url": "https://www.nced.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ncmd",
  "host": "ncmd.uscourts.gov",
  "kind": "district",
  "url": "https://www.ncmd.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 1,
   "pending": 26,
   "judges": [
    "Thomas D. Schroeder"
   ]
  },
  "mdls": []
 },
 {
  "id": "ncwd",
  "host": "ncwd.uscourts.gov",
  "kind": "district",
  "url": "https://www.ncwd.uscourts.gov/",
  "pages": {
   "rules": "https://www.ncwd.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.ncwd.uscourts.gov/forms",
   "efiling": "https://www.ncwd.uscourts.gov/cmecf-account",
   "adr": "https://www.ncwd.uscourts.gov/mediation",
   "admissions": "https://www.ncwd.uscourts.gov/attorney-admissions",
   "judges": "https://www.ncwd.uscourts.gov/judges-info"
  },
  "mdl": {
   "active": 1,
   "pending": 7,
   "judges": [
    "Kenneth D. Bell"
   ]
  },
  "mdls": []
 },
 {
  "id": "ndd",
  "host": "ndd.uscourts.gov",
  "kind": "district",
  "url": "https://www.ndd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ned",
  "host": "ned.uscourts.gov",
  "kind": "district",
  "url": "https://www.ned.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "nhd",
  "host": "nhd.uscourts.gov",
  "kind": "district",
  "url": "https://www.nhd.uscourts.gov/",
  "pages": {
   "rules": "https://www.nhd.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.nhd.uscourts.gov/forms"
  },
  "mdl": {
   "active": 1,
   "pending": 139,
   "judges": [
    "Landya B. McCafferty"
   ]
  },
  "mdls": []
 },
 {
  "id": "njd",
  "host": "njd.uscourts.gov",
  "kind": "district",
  "url": "https://www.njd.uscourts.gov/",
  "pages": {
   "admissions": "https://www.njd.uscourts.gov/attorney-admission",
   "rules": "https://www.njd.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.njd.uscourts.gov/forms/all-forms",
   "efiling": "https://www.njd.uscourts.gov/cmecf-policies-and-procedures",
   "adr": "https://www.njd.uscourts.gov/arbitration",
   "judges": "https://www.njd.uscourts.gov/judicial-preferences"
  },
  "mdl": {
   "active": 13,
   "pending": 84489,
   "judges": [
    "Claire C. Cecchi",
    "Karen M. Williams",
    "Michael A. Shipp",
    "Renee M. Bumb",
    "Jamel K. Semper",
    "Brian R. Martinotti",
    "Julien Xavier Neals",
    "Zahid N. Quraishi",
    "Christine P. O'Hearn"
   ]
  },
  "mdls": [
   {
    "number": "2243",
    "title": "Fosamax (Alendronate Sodium) Products Liability Litigation (No. II)",
    "pending": 549,
    "judgeUrl": "https://www.njd.uscourts.gov/content/karen-m-williams",
    "judge": "Karen M. Williams"
   },
   {
    "number": "2738",
    "title": "Johnson & Johnson Talcum Powder Products Marketing, Sales Practices and Products Liability Litigation",
    "pending": 68914,
    "judgeUrl": "https://www.njd.uscourts.gov/content/michael-shipp",
    "judge": "Michael A. Shipp"
   },
   {
    "number": "2789",
    "title": "Proton-Pump Inhibitor Products Liability Litigation (No. II)",
    "pending": 11321,
    "judgeUrl": "https://www.njd.uscourts.gov/content/claire-c-cecchi",
    "judge": "Claire C. Cecchi"
   },
   {
    "number": "2875",
    "title": "Valsartan, Losartan, and Irbesartan Products Liability Litigation",
    "pending": 1417,
    "judgeUrl": "https://www.njd.uscourts.gov/content/ren%C3%A9e-marie-bumb",
    "judge": "Renee M. Bumb"
   },
   {
    "number": "2921",
    "title": "Allergan Biocell Textured Breast Implant Products Liability Litigation",
    "pending": 1377,
    "judgeUrl": "https://www.njd.uscourts.gov/content/brian-r-martinotti",
    "judge": "Brian R. Martinotti"
   }
  ]
 },
 {
  "id": "nmd",
  "host": "nmd.uscourts.gov",
  "kind": "district",
  "url": "https://www.nmd.uscourts.gov/",
  "pages": {
   "rules": "https://www.nmd.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.nmd.uscourts.gov/forms",
   "judges": "https://www.nmd.uscourts.gov/judges",
   "orders": "https://www.nmd.uscourts.gov/court-info/local-rules-and-orders/general-orders"
  },
  "mdl": {
   "active": 2,
   "pending": 43,
   "judges": [
    "Robert J. Shelby",
    "Matthew L. Garcia"
   ]
  },
  "mdls": []
 },
 {
  "id": "nmid",
  "host": "nmid.uscourts.gov",
  "kind": "district",
  "url": "https://www.nmid.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "nvd",
  "host": "nvd.uscourts.gov",
  "kind": "district",
  "url": "https://www.nvd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "nyed",
  "host": "nyed.uscourts.gov",
  "kind": "district",
  "url": "https://www.nyed.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": [
   {
    "number": "3044",
    "title": "Exactech Polyethylene Orthopedic Products Liability Litigation",
    "pending": 1838
   }
  ]
 },
 {
  "id": "nynd",
  "host": "nynd.uscourts.gov",
  "kind": "district",
  "url": "https://www.nynd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "nysd",
  "host": "nysd.uscourts.gov",
  "kind": "district",
  "url": "https://www.nysd.uscourts.gov/",
  "pages": {
   "rules": "https://www.nysd.uscourts.gov/rules",
   "forms": "https://nysd.uscourts.gov/forms?field_form_category_target_id=24&title&sort_by=title",
   "efiling": "https://www.nysd.uscourts.gov/electronic-case-filing",
   "adr": "https://www.nysd.uscourts.gov/programs/mediation-adr",
   "judges": "https://www.nysd.uscourts.gov/judges"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "nywd",
  "host": "nywd.uscourts.gov",
  "kind": "district",
  "url": "https://www.nywd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ohnd",
  "host": "ohnd.uscourts.gov",
  "kind": "district",
  "url": "https://www.ohnd.uscourts.gov/",
  "pages": {
   "rules": "https://www.ohnd.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.ohnd.uscourts.gov/forms",
   "judges": "https://www.ohnd.uscourts.gov/judges"
  },
  "mdl": {
   "active": 3,
   "pending": 4856,
   "judges": [
    "Jeffrey J. Helmick",
    "Dan A. Polster",
    "J. Philip Calabrese"
   ]
  },
  "mdls": [
   {
    "number": "2804",
    "title": "National Prescription Opiate Litigation",
    "pending": 2915
   }
  ]
 },
 {
  "id": "ohsd",
  "host": "ohsd.uscourts.gov",
  "kind": "district",
  "url": "https://www.ohsd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": [
   {
    "number": "2846",
    "title": "Davol, Inc./C.R. Bard, Inc., Polypropylene Hernia Mesh Products Liability Litigation",
    "pending": 23321
   }
  ]
 },
 {
  "id": "oked",
  "host": "oked.uscourts.gov",
  "kind": "district",
  "url": "https://www.oked.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "oknd",
  "host": "oknd.uscourts.gov",
  "kind": "district",
  "url": "https://www.oknd.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 1,
   "pending": 13,
   "judges": [
    "Gregory K. Frizzell"
   ]
  },
  "mdls": []
 },
 {
  "id": "okwd",
  "host": "okwd.uscourts.gov",
  "kind": "district",
  "url": "https://www.okwd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "ord",
  "host": "ord.uscourts.gov",
  "kind": "district",
  "url": "https://www.ord.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "paed",
  "host": "paed.uscourts.gov",
  "kind": "district",
  "url": "https://www.paed.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": [
   {
    "number": "3094",
    "title": "Glucagon-like Peptide-1 Receptor Agonists (GLP-1 RAs) Products Liability Litigation",
    "pending": 3928
   }
  ]
 },
 {
  "id": "pamd",
  "host": "pamd.uscourts.gov",
  "kind": "district",
  "url": "https://www.pamd.uscourts.gov/",
  "pages": {
   "rules": "https://www.pamd.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.pamd.uscourts.gov/forms"
  },
  "mdl": {
   "active": 1,
   "pending": 4,
   "judges": [
    "Karoline Mehalchick"
   ]
  },
  "mdls": []
 },
 {
  "id": "pawd",
  "host": "pawd.uscourts.gov",
  "kind": "district",
  "url": "https://www.pawd.uscourts.gov/",
  "pages": {
   "rules": "https://www.pawd.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.pawd.uscourts.gov/forms",
   "adr": "https://www.pawd.uscourts.gov/alternative-dispute-resolution"
  },
  "mdl": {
   "active": 2,
   "pending": 636,
   "judges": [
    "W. Scott Hardy",
    "Joy Flowers Conti"
   ]
  },
  "mdls": []
 },
 {
  "id": "prd",
  "host": "prd.uscourts.gov",
  "kind": "district",
  "url": "https://www.prd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "rid",
  "host": "rid.uscourts.gov",
  "kind": "district",
  "url": "https://www.rid.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 1,
   "pending": 32,
   "judges": [
    "Mary S. McElroy"
   ]
  },
  "mdls": []
 },
 {
  "id": "scd",
  "host": "scd.uscourts.gov",
  "kind": "district",
  "url": "https://www.scd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": [
   {
    "number": "2873",
    "title": "Aqueous Film-Forming Foams Products Liability Litigation",
    "pending": 15246
   }
  ]
 },
 {
  "id": "sdd",
  "host": "sdd.uscourts.gov",
  "kind": "district",
  "url": "https://www.sdd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "tned",
  "host": "tned.uscourts.gov",
  "kind": "district",
  "url": "https://www.tned.uscourts.gov/",
  "pages": {
   "forms": "https://www.tned.uscourts.gov/forms"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "tnmd",
  "host": "tnmd.uscourts.gov",
  "kind": "district",
  "url": "https://www.tnmd.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 1,
   "pending": 13,
   "judges": [
    "Waverly D. Crenshaw, Jr"
   ]
  },
  "mdls": []
 },
 {
  "id": "tnwd",
  "host": "tnwd.uscourts.gov",
  "kind": "district",
  "url": "https://www.tnwd.uscourts.gov/",
  "pages": {
   "rules": "https://www.tnwd.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.tnwd.uscourts.gov/forms",
   "admissions": "https://www.tnwd.uscourts.gov/attorney-admissions"
  },
  "mdl": {
   "active": 1,
   "pending": 6,
   "judges": [
    "S. Thomas Anderson"
   ]
  },
  "mdls": []
 },
 {
  "id": "txed",
  "host": "txed.uscourts.gov",
  "kind": "district",
  "url": "https://www.txed.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 1,
   "pending": 59,
   "judges": [
    "Amos L. Mazzant, III"
   ]
  },
  "mdls": []
 },
 {
  "id": "txnd",
  "host": "txnd.uscourts.gov",
  "kind": "district",
  "url": "https://www.txnd.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 2,
   "pending": 146,
   "judges": [
    "David C. Godbey",
    "Ada E. Brown"
   ]
  },
  "mdls": []
 },
 {
  "id": "txwd",
  "host": "txwd.uscourts.gov",
  "kind": "district",
  "url": "https://www.txwd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "utd",
  "host": "utd.uscourts.gov",
  "kind": "district",
  "url": "https://www.utd.uscourts.gov/",
  "pages": {
   "rules": "https://www.utd.uscourts.gov/court-info/local-rules-and-orders",
   "admissions": "https://www.utd.uscourts.gov/attorney-admissions"
  },
  "mdl": {
   "active": 1,
   "pending": 6,
   "judges": [
    "David B. Barlow"
   ]
  },
  "mdls": []
 },
 {
  "id": "vaed",
  "host": "vaed.uscourts.gov",
  "kind": "district",
  "url": "https://www.vaed.uscourts.gov/",
  "pages": {
   "rules": "https://www.vaed.uscourts.gov/court-info/local-rules-and-orders",
   "forms": "https://www.vaed.uscourts.gov/forms"
  },
  "mdl": {
   "active": 1,
   "pending": 1,
   "judges": [
    "David J. Novak"
   ]
  },
  "mdls": []
 },
 {
  "id": "vawd",
  "host": "vawd.uscourts.gov",
  "kind": "district",
  "url": "https://www.vawd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "vid",
  "host": "vid.uscourts.gov",
  "kind": "district",
  "url": "https://www.vid.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "vtd",
  "host": "vtd.uscourts.gov",
  "kind": "district",
  "url": "https://www.vtd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "waed",
  "host": "waed.uscourts.gov",
  "kind": "district",
  "url": "https://www.waed.uscourts.gov/",
  "pages": {
   "forms": "https://www.waed.uscourts.gov/forms-fees/forms"
  },
  "mdl": null,
  "mdls": []
 },
 {
  "id": "wawd",
  "host": "wawd.uscourts.gov",
  "kind": "district",
  "url": "https://www.wawd.uscourts.gov/",
  "pages": {
   "admissions": "https://www.wawd.uscourts.gov/attorneys/admissions",
   "adr": "https://www.wawd.uscourts.gov/attorneys/adr",
   "judges": "https://www.wawd.uscourts.gov/judges"
  },
  "mdl": {
   "active": 1,
   "pending": 7,
   "judges": [
    "James L. Robart"
   ]
  },
  "mdls": []
 },
 {
  "id": "wied",
  "host": "wied.uscourts.gov",
  "kind": "district",
  "url": "https://www.wied.uscourts.gov/",
  "pages": {},
  "mdl": {
   "active": 2,
   "pending": 58,
   "judges": [
    "Lynn S. Adelman",
    "William C. Griesbach"
   ]
  },
  "mdls": []
 },
 {
  "id": "wiwd",
  "host": "wiwd.uscourts.gov",
  "kind": "district",
  "url": "https://www.wiwd.uscourts.gov/",
  "pages": {
   "forms": "https://www.wiwd.uscourts.gov/forms",
   "judges": "https://www.wiwd.uscourts.gov/judges"
  },
  "mdl": {
   "active": 1,
   "pending": 19,
   "judges": [
    "James D. Peterson"
   ]
  },
  "mdls": []
 },
 {
  "id": "wvnd",
  "host": "wvnd.uscourts.gov",
  "kind": "district",
  "url": "https://www.wvnd.uscourts.gov/",
  "pages": {
   "forms": "https://www.wvnd.uscourts.gov/forms"
  },
  "mdl": {
   "active": 1,
   "pending": 3,
   "judges": [
    "Thomas S. Kleeh"
   ]
  },
  "mdls": []
 },
 {
  "id": "wvsd",
  "host": "wvsd.uscourts.gov",
  "kind": "district",
  "url": "https://www.wvsd.uscourts.gov/",
  "pages": {},
  "mdl": null,
  "mdls": []
 },
 {
  "id": "wyd",
  "host": "wyd.uscourts.gov",
  "kind": "district",
  "url": "https://www.wyd.uscourts.gov/",
  "pages": {
   "forms": "https://www.wyd.uscourts.gov/forms"
  },
  "mdl": null,
  "mdls": []
 }
];
