import React, {useEffect,useLayoutEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {activityStatus,summarizeActivities,toolLabel,starterActions,type Activity,type AppKind} from './core'
import './assistant.css'
export function AssistantIcon({name='spark'}:{name?:string}) {
 const paths:Record<string,string>={plus:'M12 5v14M5 12h14',more:'M5 12h.01M12 12h.01M19 12h.01',close:'m6 6 12 12M6 18 18 6',collapse:'M4 4h16v16H4zM14 4v16m-6-11 3 3-3 3',arrow:'M12 19V5m-6 6 6-6 6 6',chevron:'m8 5 7 7-7 7',check:'m5 12 4 4L19 6',stop:'M7 7h10v10H7z',copy:'M8 8h12v12H8zM16 8V4H4v12h4',scope:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M8 12h8m-4-4v8',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z'}
 return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]??paths.spark}/></svg>
}
export function AssistantMark(){return <svg className="sw-agent-mark" width="28" height="28" viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M6 5h20a3 3 0 0 1 3 3v15a3 3 0 0 1-3 3H14l-7 4v-4H6a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3Z" stroke="currentColor" strokeWidth="1.5"/><text x="16" y="19" textAnchor="middle" fill="currentColor" fontFamily="Georgia,serif" fontSize="11" fontWeight="bold">SW</text></svg>}
export function AssistantHeader({kind,busy,onNew,onCollapse,onConnection,onLibrary}:{kind:string;busy:boolean;onNew:()=>void;onCollapse?:()=>void;onConnection:()=>void;onLibrary?:()=>void}){
 const menu=useRef<HTMLDetailsElement>(null)
 useEffect(()=>{const down=(e:PointerEvent)=>{if(!menu.current?.contains(e.target as Node)&&menu.current)menu.current.open=false};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&menu.current?.open){menu.current.open=false;menu.current.querySelector('summary')?.focus()}};document.addEventListener('pointerdown',down);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',down);document.removeEventListener('keydown',key)}},[])
 const choose=(f:()=>void)=>{if(menu.current)menu.current.open=false;f()}
 return <header className="sw-agent-header" data-sw-assistant-version="ui.2" title={`Assistant · ${kind}`}><div className="sw-agent-identity"><AssistantMark/><div><strong>Assistant</strong><small>{kind}</small></div></div><div className="sw-agent-header-actions"><button type="button" onClick={onNew} disabled={busy} aria-label="New conversation" title="New conversation"><AssistantIcon name="plus"/></button><details className="sw-agent-menu" ref={menu}><summary aria-label="Assistant options" title="Assistant options"><AssistantIcon name="more"/></summary><div className="sw-agent-menu-items">{onLibrary&&<button type="button" disabled={busy} onClick={()=>choose(onLibrary)}>Template library</button>}<button type="button" onClick={()=>choose(onConnection)}>Connection settings</button><p>Public research is not enabled in this preview.</p></div></details>{onCollapse&&<button type="button" onClick={onCollapse} aria-label="Collapse assistant" title="Collapse assistant"><AssistantIcon name="collapse"/></button>}</div></header>
}
export function AssistantOptions({children}:{children:React.ReactNode}){
 const [target,setTarget]=useState<HTMLElement|null>(null)
 useLayoutEffect(()=>{const find=()=>setTarget(document.querySelector<HTMLElement>('[data-sw-composer-options]'));find();const observer=new MutationObserver(find);observer.observe(document.body,{subtree:true,childList:true});return()=>observer.disconnect()},[])
 return target?createPortal(<div className="sw-agent-options">{children}</div>,target):null
}
export function AssistantContext({label,busy=false}:{label:string;busy?:boolean}){
 const held=useRef(label),wasBusy=useRef(false);if(!busy||!wasBusy.current)held.current=label;wasBusy.current=busy
 return <div className="sw-agent-context" title="Context available to the assistant. The request determines what to change."><AssistantIcon name="scope"/><span>{busy?held.current:label}</span><small>{busy?'In use':'Context'}</small></div>
}
export function AssistantStarters({app,mode,selected,onChoose}:{app:AppKind;mode:string;selected?:boolean;onChoose:(s:string)=>void}){
 const actions=starterActions(app,mode,selected)
 return <div className="sw-agent-empty"><span className="sw-agent-eyebrow">YOUR WORKSPACE</span><h3>{mode==='ask'?'Understand the details.':mode==='review'?'A second look.':'What would you like to work on?'}</h3><p>{mode==='write'?'Describe the result. Edits happen in the file, not just in chat.':'Get answers and specific findings without changing the file.'}</p><div className="sw-agent-starters">{actions.map(a=><button key={a.label} type="button" onClick={()=>onChoose(a.prompt)}><span><strong>{a.label}</strong><small>{a.detail}</small></span><AssistantIcon name="chevron"/></button>)}</div></div>
}
export function AssistantActivity({tools,active=false}:{tools:readonly Activity[];active?:boolean}){
 const [expanded,setExpanded]=useState<boolean|null>(null);const s=summarizeActivities(tools,active);const open=expanded??(s.running>0||s.failed>0||s.stopped>0);const current=[...tools].reverse().find(t=>activityStatus(t)==='running');const state=s.running?'running':s.failed?'failed':s.stopped?'stopped':active?'running':'done'
 if(!tools.length)return null
 return <section className="sw-agent-activity" data-state={state} aria-label="Request activity"><button className="sw-agent-activity-toggle" type="button" aria-expanded={open} onClick={()=>setExpanded(!open)}><span className={`sw-agent-state ${state}`}><AssistantIcon name={state==='done'?'check':state==='running'?'spark':'stop'}/></span><span className="sw-agent-activity-title" role="status" aria-live="polite"><strong>{current?toolLabel(current.name):s.label}</strong><small>{current?s.label:s.updates?`${s.updates} ${s.updates===1?'editing action':'editing actions'} · View activity`:'View activity'}</small></span><span className={open?'sw-agent-chevron open':'sw-agent-chevron'}><AssistantIcon name="chevron"/></span></button>{open&&<ol className="sw-agent-steps">{tools.map((t,i)=>{const status=activityStatus(t);return <li key={t.id??i} data-state={status}><span className={`sw-agent-state ${status}`}><AssistantIcon name={status==='done'?'check':status==='running'?'spark':'stop'}/></span><div><div className="sw-agent-step-line"><span>{toolLabel(t.name)}</span><small>{status==='done'?'Done':status==='running'?'Running':status==='failed'?'Failed':'Stopped'}</small></div>{!t.running&&t.summary&&t.summary!==toolLabel(t.name)&&<p>{t.summary}</p>}{t.output&&<details className="sw-agent-tool-detail"><summary>Details</summary><pre>{t.output}</pre></details>}</div></li>})}</ol>}{s.stopped>0&&<p className="sw-agent-partial">Stopped before all actions finished. Earlier changes may remain; use the available Undo control to restore them.</p>}</section>
}
export function AssistantWorking({label='Working on your request'}:{label?:string}){return <div className="sw-agent-working" role="status" aria-live="polite"><span className="sw-agent-state running"><AssistantIcon/></span><span>{label}</span></div>}
export function AssistantReplyActions({text,onReuse}:{text:string;onReuse?:()=>void}){
 const [notice,setNotice]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[])
 return <div className="sw-agent-reply-actions"><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(text);setNotice('Copied')}catch{setNotice('Copy unavailable; select the text instead.')}if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setNotice(''),2500)}}><AssistantIcon name="copy"/>Copy</button>{onReuse&&<button type="button" onClick={onReuse}>Edit request</button>}<span role="status">{notice}</span></div>
}
export function JumpToLatest({targetRef,followRef}:{targetRef:{current:HTMLElement|null};followRef:{current:boolean}}){
 const [visible,setVisible]=useState(false)
 useEffect(()=>{const el=targetRef.current;if(!el)return;const check=()=>setVisible(el.scrollHeight-el.scrollTop-el.clientHeight>110);check();el.addEventListener('scroll',check,{passive:true});const observer=new MutationObserver(check);observer.observe(el,{childList:true,subtree:true,characterData:true});const resize=typeof ResizeObserver!=='undefined'?new ResizeObserver(check):null;resize?.observe(el);window.addEventListener('resize',check);return()=>{el.removeEventListener('scroll',check);observer.disconnect();resize?.disconnect();window.removeEventListener('resize',check)}},[targetRef])
 return visible?<div className="sw-agent-jump"><button type="button" onClick={()=>{followRef.current=true;targetRef.current?.scrollTo({top:targetRef.current.scrollHeight,behavior:'instant'});setVisible(false)}}><span aria-hidden="true">↓</span> Latest response</button></div>:null
}
