import type { ToolDisplay } from '../../../agent-core/src/types'
/** Presentation-only helpers. Never changes the model transcript or executes document tools. */
export interface Activity { id?: string | undefined; name?: string | undefined; summary: string; running?: boolean | undefined; isError?: boolean | undefined; interrupted?: boolean | undefined; mutated?: boolean | undefined; output?: string | undefined; startedAt?: number | undefined; finishedAt?: number | undefined; display?: ToolDisplay | undefined }
export type ActivityState = 'running' | 'done' | 'failed' | 'stopped'
export interface Message { role: 'user' | 'assistant'; text: string; tools?: readonly Activity[] | undefined; streaming?: boolean | undefined; error?: string | undefined; isError?: boolean | undefined; snapshotId?: number | undefined; snapshot?: unknown; autoApplied?: unknown; deckProgress?: unknown; reasoning?: string | undefined; status?: string | undefined }
export function activityStatus(t:Activity):ActivityState {return t.interrupted?'stopped':t.isError?'failed':t.running?'running':'done'}
export function mergeActivities<T extends Activity>(items:readonly T[],next:T):T[]{const result=[...items];const at=next.id?result.findIndex(x=>x.id===next.id):-1;if(at<0)result.push(next);else result[at]={...result[at],...next};return result}
export function finishActivities<T extends Activity>(items:readonly T[]=[]):T[]{return items.map(t=>t.running?{...t,running:false,interrupted:true}:t)}
export function groupMessages<T extends Message>(messages:readonly T[]):{entry:T;index:number;key:number}[]{
 const result:{entry:T;index:number;key:number}[]=[]
 messages.forEach((entry,index)=>{const last=result.at(-1);if(entry.role!=='assistant'||last?.entry.role!=='assistant'){result.push({entry,index,key:index});return}
  const previous=last.entry;let tools=[...(previous.tools??[])];for(const tool of entry.tools??[])tools=mergeActivities(tools,tool)
  const parts=[previous.text,entry.text].filter(Boolean);const text=parts.length===2&&parts[0]===parts[1]?parts[0]:parts.join('\n\n')
  last.entry={...previous,...entry,text,tools,error:entry.error??previous.error,isError:entry.isError||previous.isError,snapshot:previous.snapshot??entry.snapshot,snapshotId:previous.snapshotId??entry.snapshotId,autoApplied:entry.autoApplied??previous.autoApplied,deckProgress:entry.deckProgress??previous.deckProgress,reasoning:entry.reasoning||previous.reasoning,status:entry.status||previous.status} as T;last.index=index
 });return result
}
export function summarizeActivities(items:readonly Activity[],active=false){
 const states=items.map(activityStatus);const count=(s:ActivityState)=>states.filter(x=>x===s).length
 const done=count('done'),failed=count('failed'),running=count('running'),stopped=count('stopped');const updates=items.filter(t=>t.mutated&&activityStatus(t)==='done').length
 const label=(running||(active&&done>0&&!failed&&!stopped))?`${done} completed · working`:failed?`${done} completed · ${failed} failed`:stopped?`${done} completed · stopped`:done?`${done} ${done===1?'action':'actions'} completed`:active?'Working on your request':'No actions recorded'
 return{done,failed,running,stopped,updates,label}
}
const LABELS:Record<string,string>={get_document:'Read document',read_document:'Read document',get_workbook_context:'Read workbook',read_range:'Read cell range',apply_operations:'Apply document edits',apply_changes:'Apply edits',apply_plan:'Update workbook',apply_txn:'Apply validated edits',get_slide:'Read slide',get_deck:'Read presentation',read_pages:'Read PDF pages',search_text:'Find matching text',audit_layout:'Check slide layout',create_presentation:'Create editable slides',list_slide_templates:'Read slide library',create_document:'Create document',insert_text:'Insert text',edit_text:'Edit text',edit_block:'Edit text block',markup_text:'Annotate text',compute_aggregate:'Calculate summary',load_op_doc:'Read editing guide',get_selected_text:'Read selected text',view_page:'Look at the page',view_slide:'Look at the slide',view_range:'Look at the cells',propose_operations:'Update workbook',read_format:'Read cell formatting',find_cells:'Find cells',list_templates:'Browse templates',apply_template:'Apply template',save_template:'Save as template',design_slide_html:'Design slide',insert_web_image:'Insert picture',replace_image:'Replace picture',insert_image:'Insert picture',generate_image:'Generate picture',edit_image:'Edit picture',image_search:'Search pictures',render_diagram:'Draw diagram',run_python:'Run calculation',verify_citations:'Verify citations',fetch_page:'Read web page',web_search:'Search the web',search_firm_knowledge:'Search firm knowledge',search_library:'Search library',load_firm_guide:'Read firm guide',ask_clarification:'Ask a question',read_attachment:'Read attachment',list_attachments:'List attachments',insert_html:'Insert content',replace_range:'Replace passage',insert_comment:'Add comment',set_header_footer:'Set header/footer'}
export function toolLabel(name?:string):string{if(!name)return'Document action';if(LABELS[name])return LABELS[name];const text=name.replace(/[_-]+/g,' ').trim();return text?text.charAt(0).toUpperCase()+text.slice(1):'Document action'}
export type AppKind='docs'|'sheets'|'slides'|'pdf'
export function scopeLabel(app:AppKind,s:{slide?:number;selected?:number;range?:string;page?:number;pages?:number;words?:number}):string{
 if(app==='slides')return (s.slide&&s.slide>0?`Slide ${s.slide}`:'Presentation')+(s.selected?` · ${s.selected} selected ${s.selected===1?'object':'objects'}`:'')
 if(app==='sheets')return s.range?`Selected range · ${s.range}`:'Workbook'
 if(app==='pdf')return s.words?`Selected text · ${s.words} words`:s.page&&s.page>0?`PDF · viewing page ${s.page}`:'PDF document'
 return s.words?`Selected passage · ${s.words} words`:'Current document'
}
export interface StarterAction {label:string;detail:string;prompt:string}
export function starterActions(app:AppKind,mode:string,selected=false):StarterAction[]{
 if(mode==='research')return[{label:'Research a question',detail:'Web and firm sources, cited',prompt:'Research the following question and give me a sourced summary with citations I can check: [add question]. Distinguish primary sources from commentary.'},{label:'Verify the citations',detail:'Check every cited authority',prompt:`Verify each citation in ${selected?'the selection':'this document'} against CourtListener and report which ones resolve, which do not, and any mismatched names or reporters. Do not edit the text.`},{label:'Find supporting authority',detail:'Cases, rules and articles',prompt:'Find supporting authority for the following proposition, with pinpoint citations and a one-line description of each source: [add proposition].'}]
 const subject=selected?'the selection':app==='docs'?'this document':app==='slides'?'this presentation':app==='pdf'?'this PDF':'this workbook'
 if(mode==='ask')return[{label:'Summarize',detail:'Understand the key points',prompt:`Summarize ${subject}. Distinguish stated facts from assumptions. Do not edit anything.`},{label:'Explain',detail:'Clarify content and calculations',prompt:`Explain ${subject} and flag any ambiguity. Refer to the relevant locations. Do not change any content or formatting.`}]
 if(mode==='review')return[{label:app==='slides'?'Check layout':'Check consistency',detail:'Find issues without editing',prompt:`Review ${subject} for ${app==='slides'?'text overflow, overlapping elements, inconsistent typography and alignment':'internal inconsistencies and unclear information'}. Report specific locations. Do not change any content or formatting.`},{label:'Review support',detail:'Separate claims from supporting material',prompt:`Review the claims in ${subject} against only the available document and attachments. Identify unsupported or qualified statements. Do not edit anything, invent sources, or perform public research.`}]
 if(app==='slides')return[{label:'Create a presentation',detail:'Start with editable layouts',prompt:'Create a presentation using the local slide library. Topic: [add topic]. Audience: [add audience]. Use only the information I provide; ask for missing facts. Keep text concise and preserve editable text and shapes.'},{label:'Refine layout',detail:'Improve fit and alignment',prompt:`Improve alignment and text fit in ${subject}. Preserve facts, quotations, colors and unrelated content. Read the current elements first and check the resulting layout.`},{label:'Shorten slide text',detail:'Keep the important qualifications',prompt:`Make the text in ${subject} more concise without losing facts, qualifications or citations. Preserve the existing type hierarchy and layout.`}]
 if(app==='sheets')return[{label:'Format the range',detail:'Make the data easier to read',prompt:`Format ${subject} with clear headings and appropriate number formats. Preserve all values and formulas; read the current cells first.`},{label:'Build a summary',detail:'Use calculated results',prompt:`Create a separate summary sheet from ${subject}. Read the schema first, use real formulas or calculations, and preserve the original data.`},{label:'Find inconsistencies',detail:'Mark, do not delete',prompt:`Check ${subject} for inconsistent formats, duplicates and missing values. Explain your criteria first and flag findings without deleting records or inventing replacements.`}]
 if(app==='pdf')return[{label:'Annotate a passage',detail:'Add a focused review note',prompt:`Read ${subject} and add a note explaining the main ambiguity. Do not change the underlying text or imply redaction.`},{label:'Create a report',detail:'Generate a separate PDF',prompt:'Create a separate short report PDF from the following information: [add notes]. Use headings and clear spacing. Do not alter the open PDF or invent facts.'},{label:'Add page labels',detail:'Keep the source intact',prompt:'Add simple page numbering to a separate copy of this PDF. Read the current page structure first and preserve its text and layout.'}]
 return[{label:selected?'Tighten this passage':'Improve the draft',detail:'Preserve facts and citations',prompt:`Make ${subject} clearer and more concise. Preserve factual qualifications, quotations, citations, existing styles and unrelated content.`},{label:'Normalize headings',detail:'Restore a consistent hierarchy',prompt:`Make the heading hierarchy and spacing consistent in ${subject}. Preserve body text, citations and document structure. Read existing styles first.`},{label:'Create a report',detail:'Write into the document',prompt:'Draft a short report directly into the document using these notes: [add notes]. Include clear sections and a table only when useful. No cover page unless requested; do not invent facts.'}]
}
export function settleRunMessages<T extends Message>(messages:readonly T[]):T[]{let first=messages.length;while(first>0&&messages[first-1]?.role==='assistant')first--;return messages.map((entry,i)=>i>=first?{...entry,streaming:false,tools:finishActivities(entry.tools??[])} as T:entry)}
