/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSummarizeRouteImport } from './routes/api/summarize'
import { Route as ApiQuickAskRouteImport } from './routes/api/quick-ask'
import { Route as ApiOrchestrateRouteImport } from './routes/api/orchestrate'
import { Route as ApiFollowupsRouteImport } from './routes/api/followups'
import { Route as AuthenticatedSummarizeRouteImport } from './routes/_authenticated/summarize'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedEvalRouteImport } from './routes/_authenticated/eval'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedDiscoveryRouteImport } from './routes/_authenticated/discovery'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedMattersIndexRouteImport } from './routes/_authenticated/matters.index'
import { Route as ApiReviewCellRouteImport } from './routes/api/review/cell'
import { Route as ApiPileStructureRouteImport } from './routes/api/pile/structure'
import { Route as ApiPileSessionRouteImport } from './routes/api/pile/session'
import { Route as ApiPileRerankRouteImport } from './routes/api/pile/rerank'
import { Route as ApiPileOcrRouteImport } from './routes/api/pile/ocr'
import { Route as ApiPileAskRouteImport } from './routes/api/pile/ask'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as AuthenticatedMattersSlugRouteImport } from './routes/_authenticated/matters.$slug'
import { Route as ApiPublicWebhooksDocketbirdRouteImport } from './routes/api/public/webhooks/docketbird'
import { Route as ApiPublicWebhooksCourtlistenerRouteImport } from './routes/api/public/webhooks/courtlistener'
import { Route as ApiPublicIntelRunRouteImport } from './routes/api/public/intel/run'
import { Route as ApiPublicIngestIntelRouteImport } from './routes/api/public/ingest/intel'
import { Route as ApiPublicIngestBatchesRouteImport } from './routes/api/public/ingest/batches'
import { Route as ApiPublicCalendarSyncRouteImport } from './routes/api/public/calendar/sync'
import { Route as ApiPileSessionIdRouteImport } from './routes/api/pile/session.$id'
import { Route as ApiPileScratchSessionRouteImport } from './routes/api/pile/scratch.session'
import { Route as ApiPublicIngestBatchesIdRouteImport } from './routes/api/public/ingest/batches.$id'
import { Route as ApiPileSessionIdStructureRouteImport } from './routes/api/pile/session.$id.structure'
import { Route as ApiPileSessionIdSearchRouteImport } from './routes/api/pile/session.$id.search'
import { Route as ApiPileSessionIdOcrRouteImport } from './routes/api/pile/session.$id.ocr'
import { Route as ApiPileSessionIdIngestRouteImport } from './routes/api/pile/session.$id.ingest'
import { Route as ApiPileSessionIdEmbedRouteImport } from './routes/api/pile/session.$id.embed'
import { Route as ApiPileSessionIdAskRouteImport } from './routes/api/pile/session.$id.ask'
import { Route as ApiPileScratchSessionIdRouteImport } from './routes/api/pile/scratch.session.$id'
import { Route as ApiPublicIngestBatchesIdValidateRouteImport } from './routes/api/public/ingest/batches.$id.validate'
import { Route as ApiPublicIngestBatchesIdCommitRouteImport } from './routes/api/public/ingest/batches.$id.commit'
import { Route as ApiPileScratchSessionIdSearchRouteImport } from './routes/api/pile/scratch.session.$id.search'
import { Route as ApiPileScratchSessionIdPagesRouteImport } from './routes/api/pile/scratch.session.$id.pages'
import { Route as ApiPileScratchSessionIdDocumentRouteImport } from './routes/api/pile/scratch.session.$id.document'
import { Route as ApiPileScratchDocumentIdEnqueueRouteImport } from './routes/api/pile/scratch.document.$id.enqueue'
import { Route as ApiPileScratchDocumentIdBytesRouteImport } from './routes/api/pile/scratch.document.$id.bytes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickAskRoute = ApiQuickAskRouteImport.update({
  id: '/api/quick-ask',
  path: '/api/quick-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrchestrateRoute = ApiOrchestrateRouteImport.update({
  id: '/api/orchestrate',
  path: '/api/orchestrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFollowupsRoute = ApiFollowupsRouteImport.update({
  id: '/api/followups',
  path: '/api/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSummarizeRoute = AuthenticatedSummarizeRouteImport.update({
  id: '/summarize',
  path: '/summarize',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvalRoute = AuthenticatedEvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoveryRoute = AuthenticatedDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMattersIndexRoute =
  AuthenticatedMattersIndexRouteImport.update({
    id: '/matters/',
    path: '/matters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiReviewCellRoute = ApiReviewCellRouteImport.update({
  id: '/api/review/cell',
  path: '/api/review/cell',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPileStructureRoute = ApiPileStructureRouteImport.update({
  id: '/api/pile/structure',
  path: '/api/pile/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPileSessionRoute = ApiPileSessionRouteImport.update({
  id: '/api/pile/session',
  path: '/api/pile/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPileRerankRoute = ApiPileRerankRouteImport.update({
  id: '/api/pile/rerank',
  path: '/api/pile/rerank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPileOcrRoute = ApiPileOcrRouteImport.update({
  id: '/api/pile/ocr',
  path: '/api/pile/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPileAskRoute = ApiPileAskRouteImport.update({
  id: '/api/pile/ask',
  path: '/api/pile/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMattersSlugRoute =
  AuthenticatedMattersSlugRouteImport.update({
    id: '/matters/$slug',
    path: '/matters/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksDocketbirdRoute =
  ApiPublicWebhooksDocketbirdRouteImport.update({
    id: '/api/public/webhooks/docketbird',
    path: '/api/public/webhooks/docketbird',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksCourtlistenerRoute =
  ApiPublicWebhooksCourtlistenerRouteImport.update({
    id: '/api/public/webhooks/courtlistener',
    path: '/api/public/webhooks/courtlistener',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntelRunRoute = ApiPublicIntelRunRouteImport.update({
  id: '/api/public/intel/run',
  path: '/api/public/intel/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestIntelRoute = ApiPublicIngestIntelRouteImport.update({
  id: '/api/public/ingest/intel',
  path: '/api/public/ingest/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestBatchesRoute = ApiPublicIngestBatchesRouteImport.update({
  id: '/api/public/ingest/batches',
  path: '/api/public/ingest/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarSyncRoute = ApiPublicCalendarSyncRouteImport.update({
  id: '/api/public/calendar/sync',
  path: '/api/public/calendar/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPileSessionIdRoute = ApiPileSessionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPileSessionRoute,
} as any)
const ApiPileScratchSessionRoute = ApiPileScratchSessionRouteImport.update({
  id: '/api/pile/scratch/session',
  path: '/api/pile/scratch/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestBatchesIdRoute =
  ApiPublicIngestBatchesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicIngestBatchesRoute,
  } as any)
const ApiPileSessionIdStructureRoute =
  ApiPileSessionIdStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => ApiPileSessionIdRoute,
  } as any)
const ApiPileSessionIdSearchRoute = ApiPileSessionIdSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiPileSessionIdRoute,
} as any)
const ApiPileSessionIdOcrRoute = ApiPileSessionIdOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => ApiPileSessionIdRoute,
} as any)
const ApiPileSessionIdIngestRoute = ApiPileSessionIdIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => ApiPileSessionIdRoute,
} as any)
const ApiPileSessionIdEmbedRoute = ApiPileSessionIdEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => ApiPileSessionIdRoute,
} as any)
const ApiPileSessionIdAskRoute = ApiPileSessionIdAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => ApiPileSessionIdRoute,
} as any)
const ApiPileScratchSessionIdRoute = ApiPileScratchSessionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPileScratchSessionRoute,
} as any)
const ApiPublicIngestBatchesIdValidateRoute =
  ApiPublicIngestBatchesIdValidateRouteImport.update({
    id: '/validate',
    path: '/validate',
    getParentRoute: () => ApiPublicIngestBatchesIdRoute,
  } as any)
const ApiPublicIngestBatchesIdCommitRoute =
  ApiPublicIngestBatchesIdCommitRouteImport.update({
    id: '/commit',
    path: '/commit',
    getParentRoute: () => ApiPublicIngestBatchesIdRoute,
  } as any)
const ApiPileScratchSessionIdSearchRoute =
  ApiPileScratchSessionIdSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => ApiPileScratchSessionIdRoute,
  } as any)
const ApiPileScratchSessionIdPagesRoute =
  ApiPileScratchSessionIdPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => ApiPileScratchSessionIdRoute,
  } as any)
const ApiPileScratchSessionIdDocumentRoute =
  ApiPileScratchSessionIdDocumentRouteImport.update({
    id: '/document',
    path: '/document',
    getParentRoute: () => ApiPileScratchSessionIdRoute,
  } as any)
const ApiPileScratchDocumentIdEnqueueRoute =
  ApiPileScratchDocumentIdEnqueueRouteImport.update({
    id: '/api/pile/scratch/document/$id/enqueue',
    path: '/api/pile/scratch/document/$id/enqueue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPileScratchDocumentIdBytesRoute =
  ApiPileScratchDocumentIdBytesRouteImport.update({
    id: '/api/pile/scratch/document/$id/bytes',
    path: '/api/pile/scratch/document/$id/bytes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/eval': typeof AuthenticatedEvalRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/research': typeof AuthenticatedResearchRoute
  '/summarize': typeof AuthenticatedSummarizeRoute
  '/api/followups': typeof ApiFollowupsRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/quick-ask': typeof ApiQuickAskRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/matters/$slug': typeof AuthenticatedMattersSlugRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/pile/ask': typeof ApiPileAskRoute
  '/api/pile/ocr': typeof ApiPileOcrRoute
  '/api/pile/rerank': typeof ApiPileRerankRoute
  '/api/pile/session': typeof ApiPileSessionRouteWithChildren
  '/api/pile/structure': typeof ApiPileStructureRoute
  '/api/review/cell': typeof ApiReviewCellRoute
  '/matters/': typeof AuthenticatedMattersIndexRoute
  '/api/pile/scratch/session': typeof ApiPileScratchSessionRouteWithChildren
  '/api/pile/session/$id': typeof ApiPileSessionIdRouteWithChildren
  '/api/public/calendar/sync': typeof ApiPublicCalendarSyncRoute
  '/api/public/ingest/batches': typeof ApiPublicIngestBatchesRouteWithChildren
  '/api/public/ingest/intel': typeof ApiPublicIngestIntelRoute
  '/api/public/intel/run': typeof ApiPublicIntelRunRoute
  '/api/public/webhooks/courtlistener': typeof ApiPublicWebhooksCourtlistenerRoute
  '/api/public/webhooks/docketbird': typeof ApiPublicWebhooksDocketbirdRoute
  '/api/pile/scratch/session/$id': typeof ApiPileScratchSessionIdRouteWithChildren
  '/api/pile/session/$id/ask': typeof ApiPileSessionIdAskRoute
  '/api/pile/session/$id/embed': typeof ApiPileSessionIdEmbedRoute
  '/api/pile/session/$id/ingest': typeof ApiPileSessionIdIngestRoute
  '/api/pile/session/$id/ocr': typeof ApiPileSessionIdOcrRoute
  '/api/pile/session/$id/search': typeof ApiPileSessionIdSearchRoute
  '/api/pile/session/$id/structure': typeof ApiPileSessionIdStructureRoute
  '/api/public/ingest/batches/$id': typeof ApiPublicIngestBatchesIdRouteWithChildren
  '/api/pile/scratch/document/$id/bytes': typeof ApiPileScratchDocumentIdBytesRoute
  '/api/pile/scratch/document/$id/enqueue': typeof ApiPileScratchDocumentIdEnqueueRoute
  '/api/pile/scratch/session/$id/document': typeof ApiPileScratchSessionIdDocumentRoute
  '/api/pile/scratch/session/$id/pages': typeof ApiPileScratchSessionIdPagesRoute
  '/api/pile/scratch/session/$id/search': typeof ApiPileScratchSessionIdSearchRoute
  '/api/public/ingest/batches/$id/commit': typeof ApiPublicIngestBatchesIdCommitRoute
  '/api/public/ingest/batches/$id/validate': typeof ApiPublicIngestBatchesIdValidateRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/eval': typeof AuthenticatedEvalRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/research': typeof AuthenticatedResearchRoute
  '/summarize': typeof AuthenticatedSummarizeRoute
  '/api/followups': typeof ApiFollowupsRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/quick-ask': typeof ApiQuickAskRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/': typeof AuthenticatedIndexRoute
  '/matters/$slug': typeof AuthenticatedMattersSlugRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/pile/ask': typeof ApiPileAskRoute
  '/api/pile/ocr': typeof ApiPileOcrRoute
  '/api/pile/rerank': typeof ApiPileRerankRoute
  '/api/pile/session': typeof ApiPileSessionRouteWithChildren
  '/api/pile/structure': typeof ApiPileStructureRoute
  '/api/review/cell': typeof ApiReviewCellRoute
  '/matters': typeof AuthenticatedMattersIndexRoute
  '/api/pile/scratch/session': typeof ApiPileScratchSessionRouteWithChildren
  '/api/pile/session/$id': typeof ApiPileSessionIdRouteWithChildren
  '/api/public/calendar/sync': typeof ApiPublicCalendarSyncRoute
  '/api/public/ingest/batches': typeof ApiPublicIngestBatchesRouteWithChildren
  '/api/public/ingest/intel': typeof ApiPublicIngestIntelRoute
  '/api/public/intel/run': typeof ApiPublicIntelRunRoute
  '/api/public/webhooks/courtlistener': typeof ApiPublicWebhooksCourtlistenerRoute
  '/api/public/webhooks/docketbird': typeof ApiPublicWebhooksDocketbirdRoute
  '/api/pile/scratch/session/$id': typeof ApiPileScratchSessionIdRouteWithChildren
  '/api/pile/session/$id/ask': typeof ApiPileSessionIdAskRoute
  '/api/pile/session/$id/embed': typeof ApiPileSessionIdEmbedRoute
  '/api/pile/session/$id/ingest': typeof ApiPileSessionIdIngestRoute
  '/api/pile/session/$id/ocr': typeof ApiPileSessionIdOcrRoute
  '/api/pile/session/$id/search': typeof ApiPileSessionIdSearchRoute
  '/api/pile/session/$id/structure': typeof ApiPileSessionIdStructureRoute
  '/api/public/ingest/batches/$id': typeof ApiPublicIngestBatchesIdRouteWithChildren
  '/api/pile/scratch/document/$id/bytes': typeof ApiPileScratchDocumentIdBytesRoute
  '/api/pile/scratch/document/$id/enqueue': typeof ApiPileScratchDocumentIdEnqueueRoute
  '/api/pile/scratch/session/$id/document': typeof ApiPileScratchSessionIdDocumentRoute
  '/api/pile/scratch/session/$id/pages': typeof ApiPileScratchSessionIdPagesRoute
  '/api/pile/scratch/session/$id/search': typeof ApiPileScratchSessionIdSearchRoute
  '/api/public/ingest/batches/$id/commit': typeof ApiPublicIngestBatchesIdCommitRoute
  '/api/public/ingest/batches/$id/validate': typeof ApiPublicIngestBatchesIdValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/discovery': typeof AuthenticatedDiscoveryRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/eval': typeof AuthenticatedEvalRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/summarize': typeof AuthenticatedSummarizeRoute
  '/api/followups': typeof ApiFollowupsRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/quick-ask': typeof ApiQuickAskRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/matters/$slug': typeof AuthenticatedMattersSlugRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/pile/ask': typeof ApiPileAskRoute
  '/api/pile/ocr': typeof ApiPileOcrRoute
  '/api/pile/rerank': typeof ApiPileRerankRoute
  '/api/pile/session': typeof ApiPileSessionRouteWithChildren
  '/api/pile/structure': typeof ApiPileStructureRoute
  '/api/review/cell': typeof ApiReviewCellRoute
  '/_authenticated/matters/': typeof AuthenticatedMattersIndexRoute
  '/api/pile/scratch/session': typeof ApiPileScratchSessionRouteWithChildren
  '/api/pile/session/$id': typeof ApiPileSessionIdRouteWithChildren
  '/api/public/calendar/sync': typeof ApiPublicCalendarSyncRoute
  '/api/public/ingest/batches': typeof ApiPublicIngestBatchesRouteWithChildren
  '/api/public/ingest/intel': typeof ApiPublicIngestIntelRoute
  '/api/public/intel/run': typeof ApiPublicIntelRunRoute
  '/api/public/webhooks/courtlistener': typeof ApiPublicWebhooksCourtlistenerRoute
  '/api/public/webhooks/docketbird': typeof ApiPublicWebhooksDocketbirdRoute
  '/api/pile/scratch/session/$id': typeof ApiPileScratchSessionIdRouteWithChildren
  '/api/pile/session/$id/ask': typeof ApiPileSessionIdAskRoute
  '/api/pile/session/$id/embed': typeof ApiPileSessionIdEmbedRoute
  '/api/pile/session/$id/ingest': typeof ApiPileSessionIdIngestRoute
  '/api/pile/session/$id/ocr': typeof ApiPileSessionIdOcrRoute
  '/api/pile/session/$id/search': typeof ApiPileSessionIdSearchRoute
  '/api/pile/session/$id/structure': typeof ApiPileSessionIdStructureRoute
  '/api/public/ingest/batches/$id': typeof ApiPublicIngestBatchesIdRouteWithChildren
  '/api/pile/scratch/document/$id/bytes': typeof ApiPileScratchDocumentIdBytesRoute
  '/api/pile/scratch/document/$id/enqueue': typeof ApiPileScratchDocumentIdEnqueueRoute
  '/api/pile/scratch/session/$id/document': typeof ApiPileScratchSessionIdDocumentRoute
  '/api/pile/scratch/session/$id/pages': typeof ApiPileScratchSessionIdPagesRoute
  '/api/pile/scratch/session/$id/search': typeof ApiPileScratchSessionIdSearchRoute
  '/api/public/ingest/batches/$id/commit': typeof ApiPublicIngestBatchesIdCommitRoute
  '/api/public/ingest/batches/$id/validate': typeof ApiPublicIngestBatchesIdValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/conversations'
    | '/discovery'
    | '/docs'
    | '/eval'
    | '/library'
    | '/research'
    | '/summarize'
    | '/api/followups'
    | '/api/orchestrate'
    | '/api/quick-ask'
    | '/api/summarize'
    | '/api/upload'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/matters/$slug'
    | '/api/auth/me'
    | '/api/pile/ask'
    | '/api/pile/ocr'
    | '/api/pile/rerank'
    | '/api/pile/session'
    | '/api/pile/structure'
    | '/api/review/cell'
    | '/matters/'
    | '/api/pile/scratch/session'
    | '/api/pile/session/$id'
    | '/api/public/calendar/sync'
    | '/api/public/ingest/batches'
    | '/api/public/ingest/intel'
    | '/api/public/intel/run'
    | '/api/public/webhooks/courtlistener'
    | '/api/public/webhooks/docketbird'
    | '/api/pile/scratch/session/$id'
    | '/api/pile/session/$id/ask'
    | '/api/pile/session/$id/embed'
    | '/api/pile/session/$id/ingest'
    | '/api/pile/session/$id/ocr'
    | '/api/pile/session/$id/search'
    | '/api/pile/session/$id/structure'
    | '/api/public/ingest/batches/$id'
    | '/api/pile/scratch/document/$id/bytes'
    | '/api/pile/scratch/document/$id/enqueue'
    | '/api/pile/scratch/session/$id/document'
    | '/api/pile/scratch/session/$id/pages'
    | '/api/pile/scratch/session/$id/search'
    | '/api/public/ingest/batches/$id/commit'
    | '/api/public/ingest/batches/$id/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/calendar'
    | '/conversations'
    | '/discovery'
    | '/docs'
    | '/eval'
    | '/library'
    | '/research'
    | '/summarize'
    | '/api/followups'
    | '/api/orchestrate'
    | '/api/quick-ask'
    | '/api/summarize'
    | '/api/upload'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/'
    | '/matters/$slug'
    | '/api/auth/me'
    | '/api/pile/ask'
    | '/api/pile/ocr'
    | '/api/pile/rerank'
    | '/api/pile/session'
    | '/api/pile/structure'
    | '/api/review/cell'
    | '/matters'
    | '/api/pile/scratch/session'
    | '/api/pile/session/$id'
    | '/api/public/calendar/sync'
    | '/api/public/ingest/batches'
    | '/api/public/ingest/intel'
    | '/api/public/intel/run'
    | '/api/public/webhooks/courtlistener'
    | '/api/public/webhooks/docketbird'
    | '/api/pile/scratch/session/$id'
    | '/api/pile/session/$id/ask'
    | '/api/pile/session/$id/embed'
    | '/api/pile/session/$id/ingest'
    | '/api/pile/session/$id/ocr'
    | '/api/pile/session/$id/search'
    | '/api/pile/session/$id/structure'
    | '/api/public/ingest/batches/$id'
    | '/api/pile/scratch/document/$id/bytes'
    | '/api/pile/scratch/document/$id/enqueue'
    | '/api/pile/scratch/session/$id/document'
    | '/api/pile/scratch/session/$id/pages'
    | '/api/pile/scratch/session/$id/search'
    | '/api/public/ingest/batches/$id/commit'
    | '/api/public/ingest/batches/$id/validate'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/conversations'
    | '/_authenticated/discovery'
    | '/_authenticated/docs'
    | '/_authenticated/eval'
    | '/_authenticated/library'
    | '/_authenticated/research'
    | '/_authenticated/summarize'
    | '/api/followups'
    | '/api/orchestrate'
    | '/api/quick-ask'
    | '/api/summarize'
    | '/api/upload'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/_authenticated/'
    | '/_authenticated/matters/$slug'
    | '/api/auth/me'
    | '/api/pile/ask'
    | '/api/pile/ocr'
    | '/api/pile/rerank'
    | '/api/pile/session'
    | '/api/pile/structure'
    | '/api/review/cell'
    | '/_authenticated/matters/'
    | '/api/pile/scratch/session'
    | '/api/pile/session/$id'
    | '/api/public/calendar/sync'
    | '/api/public/ingest/batches'
    | '/api/public/ingest/intel'
    | '/api/public/intel/run'
    | '/api/public/webhooks/courtlistener'
    | '/api/public/webhooks/docketbird'
    | '/api/pile/scratch/session/$id'
    | '/api/pile/session/$id/ask'
    | '/api/pile/session/$id/embed'
    | '/api/pile/session/$id/ingest'
    | '/api/pile/session/$id/ocr'
    | '/api/pile/session/$id/search'
    | '/api/pile/session/$id/structure'
    | '/api/public/ingest/batches/$id'
    | '/api/pile/scratch/document/$id/bytes'
    | '/api/pile/scratch/document/$id/enqueue'
    | '/api/pile/scratch/session/$id/document'
    | '/api/pile/scratch/session/$id/pages'
    | '/api/pile/scratch/session/$id/search'
    | '/api/public/ingest/batches/$id/commit'
    | '/api/public/ingest/batches/$id/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiFollowupsRoute: typeof ApiFollowupsRoute
  ApiOrchestrateRoute: typeof ApiOrchestrateRoute
  ApiQuickAskRoute: typeof ApiQuickAskRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiPileAskRoute: typeof ApiPileAskRoute
  ApiPileOcrRoute: typeof ApiPileOcrRoute
  ApiPileRerankRoute: typeof ApiPileRerankRoute
  ApiPileSessionRoute: typeof ApiPileSessionRouteWithChildren
  ApiPileStructureRoute: typeof ApiPileStructureRoute
  ApiReviewCellRoute: typeof ApiReviewCellRoute
  ApiPileScratchSessionRoute: typeof ApiPileScratchSessionRouteWithChildren
  ApiPublicCalendarSyncRoute: typeof ApiPublicCalendarSyncRoute
  ApiPublicIngestBatchesRoute: typeof ApiPublicIngestBatchesRouteWithChildren
  ApiPublicIngestIntelRoute: typeof ApiPublicIngestIntelRoute
  ApiPublicIntelRunRoute: typeof ApiPublicIntelRunRoute
  ApiPublicWebhooksCourtlistenerRoute: typeof ApiPublicWebhooksCourtlistenerRoute
  ApiPublicWebhooksDocketbirdRoute: typeof ApiPublicWebhooksDocketbirdRoute
  ApiPileScratchDocumentIdBytesRoute: typeof ApiPileScratchDocumentIdBytesRoute
  ApiPileScratchDocumentIdEnqueueRoute: typeof ApiPileScratchDocumentIdEnqueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quick-ask': {
      id: '/api/quick-ask'
      path: '/api/quick-ask'
      fullPath: '/api/quick-ask'
      preLoaderRoute: typeof ApiQuickAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orchestrate': {
      id: '/api/orchestrate'
      path: '/api/orchestrate'
      fullPath: '/api/orchestrate'
      preLoaderRoute: typeof ApiOrchestrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/followups': {
      id: '/api/followups'
      path: '/api/followups'
      fullPath: '/api/followups'
      preLoaderRoute: typeof ApiFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/summarize': {
      id: '/_authenticated/summarize'
      path: '/summarize'
      fullPath: '/summarize'
      preLoaderRoute: typeof AuthenticatedSummarizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eval': {
      id: '/_authenticated/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof AuthenticatedEvalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discovery': {
      id: '/_authenticated/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matters/': {
      id: '/_authenticated/matters/'
      path: '/matters'
      fullPath: '/matters/'
      preLoaderRoute: typeof AuthenticatedMattersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/review/cell': {
      id: '/api/review/cell'
      path: '/api/review/cell'
      fullPath: '/api/review/cell'
      preLoaderRoute: typeof ApiReviewCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pile/structure': {
      id: '/api/pile/structure'
      path: '/api/pile/structure'
      fullPath: '/api/pile/structure'
      preLoaderRoute: typeof ApiPileStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pile/session': {
      id: '/api/pile/session'
      path: '/api/pile/session'
      fullPath: '/api/pile/session'
      preLoaderRoute: typeof ApiPileSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pile/rerank': {
      id: '/api/pile/rerank'
      path: '/api/pile/rerank'
      fullPath: '/api/pile/rerank'
      preLoaderRoute: typeof ApiPileRerankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pile/ocr': {
      id: '/api/pile/ocr'
      path: '/api/pile/ocr'
      fullPath: '/api/pile/ocr'
      preLoaderRoute: typeof ApiPileOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pile/ask': {
      id: '/api/pile/ask'
      path: '/api/pile/ask'
      fullPath: '/api/pile/ask'
      preLoaderRoute: typeof ApiPileAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/matters/$slug': {
      id: '/_authenticated/matters/$slug'
      path: '/matters/$slug'
      fullPath: '/matters/$slug'
      preLoaderRoute: typeof AuthenticatedMattersSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/docketbird': {
      id: '/api/public/webhooks/docketbird'
      path: '/api/public/webhooks/docketbird'
      fullPath: '/api/public/webhooks/docketbird'
      preLoaderRoute: typeof ApiPublicWebhooksDocketbirdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/courtlistener': {
      id: '/api/public/webhooks/courtlistener'
      path: '/api/public/webhooks/courtlistener'
      fullPath: '/api/public/webhooks/courtlistener'
      preLoaderRoute: typeof ApiPublicWebhooksCourtlistenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/intel/run': {
      id: '/api/public/intel/run'
      path: '/api/public/intel/run'
      fullPath: '/api/public/intel/run'
      preLoaderRoute: typeof ApiPublicIntelRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/intel': {
      id: '/api/public/ingest/intel'
      path: '/api/public/ingest/intel'
      fullPath: '/api/public/ingest/intel'
      preLoaderRoute: typeof ApiPublicIngestIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/batches': {
      id: '/api/public/ingest/batches'
      path: '/api/public/ingest/batches'
      fullPath: '/api/public/ingest/batches'
      preLoaderRoute: typeof ApiPublicIngestBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/sync': {
      id: '/api/public/calendar/sync'
      path: '/api/public/calendar/sync'
      fullPath: '/api/public/calendar/sync'
      preLoaderRoute: typeof ApiPublicCalendarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pile/session/$id': {
      id: '/api/pile/session/$id'
      path: '/$id'
      fullPath: '/api/pile/session/$id'
      preLoaderRoute: typeof ApiPileSessionIdRouteImport
      parentRoute: typeof ApiPileSessionRoute
    }
    '/api/pile/scratch/session': {
      id: '/api/pile/scratch/session'
      path: '/api/pile/scratch/session'
      fullPath: '/api/pile/scratch/session'
      preLoaderRoute: typeof ApiPileScratchSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/batches/$id': {
      id: '/api/public/ingest/batches/$id'
      path: '/$id'
      fullPath: '/api/public/ingest/batches/$id'
      preLoaderRoute: typeof ApiPublicIngestBatchesIdRouteImport
      parentRoute: typeof ApiPublicIngestBatchesRoute
    }
    '/api/pile/session/$id/structure': {
      id: '/api/pile/session/$id/structure'
      path: '/structure'
      fullPath: '/api/pile/session/$id/structure'
      preLoaderRoute: typeof ApiPileSessionIdStructureRouteImport
      parentRoute: typeof ApiPileSessionIdRoute
    }
    '/api/pile/session/$id/search': {
      id: '/api/pile/session/$id/search'
      path: '/search'
      fullPath: '/api/pile/session/$id/search'
      preLoaderRoute: typeof ApiPileSessionIdSearchRouteImport
      parentRoute: typeof ApiPileSessionIdRoute
    }
    '/api/pile/session/$id/ocr': {
      id: '/api/pile/session/$id/ocr'
      path: '/ocr'
      fullPath: '/api/pile/session/$id/ocr'
      preLoaderRoute: typeof ApiPileSessionIdOcrRouteImport
      parentRoute: typeof ApiPileSessionIdRoute
    }
    '/api/pile/session/$id/ingest': {
      id: '/api/pile/session/$id/ingest'
      path: '/ingest'
      fullPath: '/api/pile/session/$id/ingest'
      preLoaderRoute: typeof ApiPileSessionIdIngestRouteImport
      parentRoute: typeof ApiPileSessionIdRoute
    }
    '/api/pile/session/$id/embed': {
      id: '/api/pile/session/$id/embed'
      path: '/embed'
      fullPath: '/api/pile/session/$id/embed'
      preLoaderRoute: typeof ApiPileSessionIdEmbedRouteImport
      parentRoute: typeof ApiPileSessionIdRoute
    }
    '/api/pile/session/$id/ask': {
      id: '/api/pile/session/$id/ask'
      path: '/ask'
      fullPath: '/api/pile/session/$id/ask'
      preLoaderRoute: typeof ApiPileSessionIdAskRouteImport
      parentRoute: typeof ApiPileSessionIdRoute
    }
    '/api/pile/scratch/session/$id': {
      id: '/api/pile/scratch/session/$id'
      path: '/$id'
      fullPath: '/api/pile/scratch/session/$id'
      preLoaderRoute: typeof ApiPileScratchSessionIdRouteImport
      parentRoute: typeof ApiPileScratchSessionRoute
    }
    '/api/public/ingest/batches/$id/validate': {
      id: '/api/public/ingest/batches/$id/validate'
      path: '/validate'
      fullPath: '/api/public/ingest/batches/$id/validate'
      preLoaderRoute: typeof ApiPublicIngestBatchesIdValidateRouteImport
      parentRoute: typeof ApiPublicIngestBatchesIdRoute
    }
    '/api/public/ingest/batches/$id/commit': {
      id: '/api/public/ingest/batches/$id/commit'
      path: '/commit'
      fullPath: '/api/public/ingest/batches/$id/commit'
      preLoaderRoute: typeof ApiPublicIngestBatchesIdCommitRouteImport
      parentRoute: typeof ApiPublicIngestBatchesIdRoute
    }
    '/api/pile/scratch/session/$id/search': {
      id: '/api/pile/scratch/session/$id/search'
      path: '/search'
      fullPath: '/api/pile/scratch/session/$id/search'
      preLoaderRoute: typeof ApiPileScratchSessionIdSearchRouteImport
      parentRoute: typeof ApiPileScratchSessionIdRoute
    }
    '/api/pile/scratch/session/$id/pages': {
      id: '/api/pile/scratch/session/$id/pages'
      path: '/pages'
      fullPath: '/api/pile/scratch/session/$id/pages'
      preLoaderRoute: typeof ApiPileScratchSessionIdPagesRouteImport
      parentRoute: typeof ApiPileScratchSessionIdRoute
    }
    '/api/pile/scratch/session/$id/document': {
      id: '/api/pile/scratch/session/$id/document'
      path: '/document'
      fullPath: '/api/pile/scratch/session/$id/document'
      preLoaderRoute: typeof ApiPileScratchSessionIdDocumentRouteImport
      parentRoute: typeof ApiPileScratchSessionIdRoute
    }
    '/api/pile/scratch/document/$id/enqueue': {
      id: '/api/pile/scratch/document/$id/enqueue'
      path: '/api/pile/scratch/document/$id/enqueue'
      fullPath: '/api/pile/scratch/document/$id/enqueue'
      preLoaderRoute: typeof ApiPileScratchDocumentIdEnqueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pile/scratch/document/$id/bytes': {
      id: '/api/pile/scratch/document/$id/bytes'
      path: '/api/pile/scratch/document/$id/bytes'
      fullPath: '/api/pile/scratch/document/$id/bytes'
      preLoaderRoute: typeof ApiPileScratchDocumentIdBytesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDiscoveryRoute: typeof AuthenticatedDiscoveryRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedEvalRoute: typeof AuthenticatedEvalRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedSummarizeRoute: typeof AuthenticatedSummarizeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMattersSlugRoute: typeof AuthenticatedMattersSlugRoute
  AuthenticatedMattersIndexRoute: typeof AuthenticatedMattersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDiscoveryRoute: AuthenticatedDiscoveryRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedEvalRoute: AuthenticatedEvalRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedSummarizeRoute: AuthenticatedSummarizeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMattersSlugRoute: AuthenticatedMattersSlugRoute,
  AuthenticatedMattersIndexRoute: AuthenticatedMattersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiPileSessionIdRouteChildren {
  ApiPileSessionIdAskRoute: typeof ApiPileSessionIdAskRoute
  ApiPileSessionIdEmbedRoute: typeof ApiPileSessionIdEmbedRoute
  ApiPileSessionIdIngestRoute: typeof ApiPileSessionIdIngestRoute
  ApiPileSessionIdOcrRoute: typeof ApiPileSessionIdOcrRoute
  ApiPileSessionIdSearchRoute: typeof ApiPileSessionIdSearchRoute
  ApiPileSessionIdStructureRoute: typeof ApiPileSessionIdStructureRoute
}

const ApiPileSessionIdRouteChildren: ApiPileSessionIdRouteChildren = {
  ApiPileSessionIdAskRoute: ApiPileSessionIdAskRoute,
  ApiPileSessionIdEmbedRoute: ApiPileSessionIdEmbedRoute,
  ApiPileSessionIdIngestRoute: ApiPileSessionIdIngestRoute,
  ApiPileSessionIdOcrRoute: ApiPileSessionIdOcrRoute,
  ApiPileSessionIdSearchRoute: ApiPileSessionIdSearchRoute,
  ApiPileSessionIdStructureRoute: ApiPileSessionIdStructureRoute,
}

const ApiPileSessionIdRouteWithChildren =
  ApiPileSessionIdRoute._addFileChildren(ApiPileSessionIdRouteChildren)

interface ApiPileSessionRouteChildren {
  ApiPileSessionIdRoute: typeof ApiPileSessionIdRouteWithChildren
}

const ApiPileSessionRouteChildren: ApiPileSessionRouteChildren = {
  ApiPileSessionIdRoute: ApiPileSessionIdRouteWithChildren,
}

const ApiPileSessionRouteWithChildren = ApiPileSessionRoute._addFileChildren(
  ApiPileSessionRouteChildren,
)

interface ApiPileScratchSessionIdRouteChildren {
  ApiPileScratchSessionIdDocumentRoute: typeof ApiPileScratchSessionIdDocumentRoute
  ApiPileScratchSessionIdPagesRoute: typeof ApiPileScratchSessionIdPagesRoute
  ApiPileScratchSessionIdSearchRoute: typeof ApiPileScratchSessionIdSearchRoute
}

const ApiPileScratchSessionIdRouteChildren: ApiPileScratchSessionIdRouteChildren =
  {
    ApiPileScratchSessionIdDocumentRoute: ApiPileScratchSessionIdDocumentRoute,
    ApiPileScratchSessionIdPagesRoute: ApiPileScratchSessionIdPagesRoute,
    ApiPileScratchSessionIdSearchRoute: ApiPileScratchSessionIdSearchRoute,
  }

const ApiPileScratchSessionIdRouteWithChildren =
  ApiPileScratchSessionIdRoute._addFileChildren(
    ApiPileScratchSessionIdRouteChildren,
  )

interface ApiPileScratchSessionRouteChildren {
  ApiPileScratchSessionIdRoute: typeof ApiPileScratchSessionIdRouteWithChildren
}

const ApiPileScratchSessionRouteChildren: ApiPileScratchSessionRouteChildren = {
  ApiPileScratchSessionIdRoute: ApiPileScratchSessionIdRouteWithChildren,
}

const ApiPileScratchSessionRouteWithChildren =
  ApiPileScratchSessionRoute._addFileChildren(
    ApiPileScratchSessionRouteChildren,
  )

interface ApiPublicIngestBatchesIdRouteChildren {
  ApiPublicIngestBatchesIdCommitRoute: typeof ApiPublicIngestBatchesIdCommitRoute
  ApiPublicIngestBatchesIdValidateRoute: typeof ApiPublicIngestBatchesIdValidateRoute
}

const ApiPublicIngestBatchesIdRouteChildren: ApiPublicIngestBatchesIdRouteChildren =
  {
    ApiPublicIngestBatchesIdCommitRoute: ApiPublicIngestBatchesIdCommitRoute,
    ApiPublicIngestBatchesIdValidateRoute:
      ApiPublicIngestBatchesIdValidateRoute,
  }

const ApiPublicIngestBatchesIdRouteWithChildren =
  ApiPublicIngestBatchesIdRoute._addFileChildren(
    ApiPublicIngestBatchesIdRouteChildren,
  )

interface ApiPublicIngestBatchesRouteChildren {
  ApiPublicIngestBatchesIdRoute: typeof ApiPublicIngestBatchesIdRouteWithChildren
}

const ApiPublicIngestBatchesRouteChildren: ApiPublicIngestBatchesRouteChildren =
  {
    ApiPublicIngestBatchesIdRoute: ApiPublicIngestBatchesIdRouteWithChildren,
  }

const ApiPublicIngestBatchesRouteWithChildren =
  ApiPublicIngestBatchesRoute._addFileChildren(
    ApiPublicIngestBatchesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiFollowupsRoute: ApiFollowupsRoute,
  ApiOrchestrateRoute: ApiOrchestrateRoute,
  ApiQuickAskRoute: ApiQuickAskRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiPileAskRoute: ApiPileAskRoute,
  ApiPileOcrRoute: ApiPileOcrRoute,
  ApiPileRerankRoute: ApiPileRerankRoute,
  ApiPileSessionRoute: ApiPileSessionRouteWithChildren,
  ApiPileStructureRoute: ApiPileStructureRoute,
  ApiReviewCellRoute: ApiReviewCellRoute,
  ApiPileScratchSessionRoute: ApiPileScratchSessionRouteWithChildren,
  ApiPublicCalendarSyncRoute: ApiPublicCalendarSyncRoute,
  ApiPublicIngestBatchesRoute: ApiPublicIngestBatchesRouteWithChildren,
  ApiPublicIngestIntelRoute: ApiPublicIngestIntelRoute,
  ApiPublicIntelRunRoute: ApiPublicIntelRunRoute,
  ApiPublicWebhooksCourtlistenerRoute: ApiPublicWebhooksCourtlistenerRoute,
  ApiPublicWebhooksDocketbirdRoute: ApiPublicWebhooksDocketbirdRoute,
  ApiPileScratchDocumentIdBytesRoute: ApiPileScratchDocumentIdBytesRoute,
  ApiPileScratchDocumentIdEnqueueRoute: ApiPileScratchDocumentIdEnqueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
