/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiWorkflowsRouteImport } from './routes/api/workflows'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiTracesRouteImport } from './routes/api/traces'
import { Route as ApiSummarizeRouteImport } from './routes/api/summarize'
import { Route as ApiQuickAskRouteImport } from './routes/api/quick-ask'
import { Route as ApiOrchestrateRouteImport } from './routes/api/orchestrate'
import { Route as ApiFollowupsRouteImport } from './routes/api/followups'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedSummarizeRouteImport } from './routes/_authenticated/summarize'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedInspectorRouteImport } from './routes/_authenticated/inspector'
import { Route as AuthenticatedEvalRouteImport } from './routes/_authenticated/eval'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedDiscoveryRouteImport } from './routes/_authenticated/discovery'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedOfficeIndexRouteImport } from './routes/_authenticated/office.index'
import { Route as AuthenticatedMattersIndexRouteImport } from './routes/_authenticated/matters.index'
import { Route as AuthenticatedDraftsIndexRouteImport } from './routes/_authenticated/drafts.index'
import { Route as ApiWriterStreamRouteImport } from './routes/api/writer/stream'
import { Route as ApiWriterDocsRouteImport } from './routes/api/writer/docs'
import { Route as ApiWorkbenchSplatRouteImport } from './routes/api/workbench/$'
import { Route as ApiReviewCellRouteImport } from './routes/api/review/cell'
import { Route as ApiPileStructureRouteImport } from './routes/api/pile/structure'
import { Route as ApiPileRerankRouteImport } from './routes/api/pile/rerank'
import { Route as ApiPileOcrRouteImport } from './routes/api/pile/ocr'
import { Route as ApiPileAskRouteImport } from './routes/api/pile/ask'
import { Route as ApiOfficeStreamRouteImport } from './routes/api/office/stream'
import { Route as ApiOfficeJwksRouteImport } from './routes/api/office/jwks'
import { Route as ApiOfficeDocsRouteImport } from './routes/api/office/docs'
import { Route as ApiKbSearchRouteImport } from './routes/api/kb/search'
import { Route as ApiKbIngestRouteImport } from './routes/api/kb/ingest'
import { Route as ApiKbDocumentsRouteImport } from './routes/api/kb/documents'
import { Route as ApiKbAskRouteImport } from './routes/api/kb/ask'
import { Route as ApiDiscoveryAnalyzeRouteImport } from './routes/api/discovery/analyze'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiArchiveSplatRouteImport } from './routes/api/archive/$'
import { Route as AuthenticatedMattersSlugRouteImport } from './routes/_authenticated/matters.$slug'
import { Route as AuthenticatedDraftsDraftIdRouteImport } from './routes/_authenticated/drafts.$draftId'
import { Route as AuthenticatedArchiveJurisdictionsRouteImport } from './routes/_authenticated/archive.jurisdictions'
import { Route as AuthenticatedArchiveFederalRouteImport } from './routes/_authenticated/archive.federal'
import { Route as AuthenticatedArchiveCourtsRouteImport } from './routes/_authenticated/archive.courts'
import { Route as AuthenticatedOfficeSlidesIndexRouteImport } from './routes/_authenticated/office.slides.index'
import { Route as AuthenticatedOfficeSheetsIndexRouteImport } from './routes/_authenticated/office.sheets.index'
import { Route as AuthenticatedOfficeDraftsIndexRouteImport } from './routes/_authenticated/office.drafts.index'
import { Route as ApiPublicWebhooksDocketbirdRouteImport } from './routes/api/public/webhooks/docketbird'
import { Route as ApiPublicWebhooksCourtlistenerRouteImport } from './routes/api/public/webhooks/courtlistener'
import { Route as ApiPublicOfficeJwksRouteImport } from './routes/api/public/office/jwks'
import { Route as ApiPublicMattersSyncRouteImport } from './routes/api/public/matters/sync'
import { Route as ApiPublicIntelRunRouteImport } from './routes/api/public/intel/run'
import { Route as ApiPublicIngestIntelRouteImport } from './routes/api/public/ingest/intel'
import { Route as ApiPublicIngestBatchesRouteImport } from './routes/api/public/ingest/batches'
import { Route as ApiPublicCalendarSyncRouteImport } from './routes/api/public/calendar/sync'
import { Route as AuthenticatedOfficeSlidesDocIdRouteImport } from './routes/_authenticated/office.slides.$docId'
import { Route as AuthenticatedOfficeSheetsDocIdRouteImport } from './routes/_authenticated/office.sheets.$docId'
import { Route as AuthenticatedOfficeDraftsDraftIdRouteImport } from './routes/_authenticated/office.drafts.$draftId'
import { Route as ApiWriterDocsDraftIdRecoveryRouteImport } from './routes/api/writer/docs.$draftId.recovery'
import { Route as ApiWriterDocsDraftIdContentRouteImport } from './routes/api/writer/docs.$draftId.content'
import { Route as ApiPublicIngestBatchesIdRouteImport } from './routes/api/public/ingest/batches.$id'
import { Route as ApiOfficeDocsDocIdRecoveryRouteImport } from './routes/api/office/docs.$docId.recovery'
import { Route as ApiOfficeDocsDocIdContentRouteImport } from './routes/api/office/docs.$docId.content'
import { Route as ApiPublicIngestBatchesIdValidateRouteImport } from './routes/api/public/ingest/batches.$id.validate'
import { Route as ApiPublicIngestBatchesIdCommitRouteImport } from './routes/api/public/ingest/batches.$id.commit'
import { Route as ApiPublicOfficeEngineDocsDocIdContentRouteImport } from './routes/api/public/office/engine.docs.$docId.content'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiWorkflowsRoute = ApiWorkflowsRouteImport.update({
  id: '/api/workflows',
  path: '/api/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTracesRoute = ApiTracesRouteImport.update({
  id: '/api/traces',
  path: '/api/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickAskRoute = ApiQuickAskRouteImport.update({
  id: '/api/quick-ask',
  path: '/api/quick-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrchestrateRoute = ApiOrchestrateRouteImport.update({
  id: '/api/orchestrate',
  path: '/api/orchestrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFollowupsRoute = ApiFollowupsRouteImport.update({
  id: '/api/followups',
  path: '/api/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSummarizeRoute = AuthenticatedSummarizeRouteImport.update({
  id: '/summarize',
  path: '/summarize',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectorRoute = AuthenticatedInspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvalRoute = AuthenticatedEvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoveryRoute = AuthenticatedDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficeIndexRoute =
  AuthenticatedOfficeIndexRouteImport.update({
    id: '/office/',
    path: '/office/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMattersIndexRoute =
  AuthenticatedMattersIndexRouteImport.update({
    id: '/matters/',
    path: '/matters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDraftsIndexRoute =
  AuthenticatedDraftsIndexRouteImport.update({
    id: '/drafts/',
    path: '/drafts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiWriterStreamRoute = ApiWriterStreamRouteImport.update({
  id: '/api/writer/stream',
  path: '/api/writer/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWriterDocsRoute = ApiWriterDocsRouteImport.update({
  id: '/api/writer/docs',
  path: '/api/writer/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkbenchSplatRoute = ApiWorkbenchSplatRouteImport.update({
  id: '/api/workbench/$',
  path: '/api/workbench/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewCellRoute = ApiReviewCellRouteImport.update({
  id: '/api/review/cell',
  path: '/api/review/cell',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPileStructureRoute = ApiPileStructureRouteImport.update({
  id: '/api/pile/structure',
  path: '/api/pile/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPileRerankRoute = ApiPileRerankRouteImport.update({
  id: '/api/pile/rerank',
  path: '/api/pile/rerank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPileOcrRoute = ApiPileOcrRouteImport.update({
  id: '/api/pile/ocr',
  path: '/api/pile/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPileAskRoute = ApiPileAskRouteImport.update({
  id: '/api/pile/ask',
  path: '/api/pile/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfficeStreamRoute = ApiOfficeStreamRouteImport.update({
  id: '/api/office/stream',
  path: '/api/office/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfficeJwksRoute = ApiOfficeJwksRouteImport.update({
  id: '/api/office/jwks',
  path: '/api/office/jwks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfficeDocsRoute = ApiOfficeDocsRouteImport.update({
  id: '/api/office/docs',
  path: '/api/office/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKbSearchRoute = ApiKbSearchRouteImport.update({
  id: '/api/kb/search',
  path: '/api/kb/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKbIngestRoute = ApiKbIngestRouteImport.update({
  id: '/api/kb/ingest',
  path: '/api/kb/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKbDocumentsRoute = ApiKbDocumentsRouteImport.update({
  id: '/api/kb/documents',
  path: '/api/kb/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKbAskRoute = ApiKbAskRouteImport.update({
  id: '/api/kb/ask',
  path: '/api/kb/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoveryAnalyzeRoute = ApiDiscoveryAnalyzeRouteImport.update({
  id: '/api/discovery/analyze',
  path: '/api/discovery/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveSplatRoute = ApiArchiveSplatRouteImport.update({
  id: '/api/archive/$',
  path: '/api/archive/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMattersSlugRoute =
  AuthenticatedMattersSlugRouteImport.update({
    id: '/matters/$slug',
    path: '/matters/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDraftsDraftIdRoute =
  AuthenticatedDraftsDraftIdRouteImport.update({
    id: '/drafts/$draftId',
    path: '/drafts/$draftId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveJurisdictionsRoute =
  AuthenticatedArchiveJurisdictionsRouteImport.update({
    id: '/archive/jurisdictions',
    path: '/archive/jurisdictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveFederalRoute =
  AuthenticatedArchiveFederalRouteImport.update({
    id: '/archive/federal',
    path: '/archive/federal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveCourtsRoute =
  AuthenticatedArchiveCourtsRouteImport.update({
    id: '/archive/courts',
    path: '/archive/courts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficeSlidesIndexRoute =
  AuthenticatedOfficeSlidesIndexRouteImport.update({
    id: '/office/slides/',
    path: '/office/slides/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficeSheetsIndexRoute =
  AuthenticatedOfficeSheetsIndexRouteImport.update({
    id: '/office/sheets/',
    path: '/office/sheets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficeDraftsIndexRoute =
  AuthenticatedOfficeDraftsIndexRouteImport.update({
    id: '/office/drafts/',
    path: '/office/drafts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksDocketbirdRoute =
  ApiPublicWebhooksDocketbirdRouteImport.update({
    id: '/api/public/webhooks/docketbird',
    path: '/api/public/webhooks/docketbird',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksCourtlistenerRoute =
  ApiPublicWebhooksCourtlistenerRouteImport.update({
    id: '/api/public/webhooks/courtlistener',
    path: '/api/public/webhooks/courtlistener',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOfficeJwksRoute = ApiPublicOfficeJwksRouteImport.update({
  id: '/api/public/office/jwks',
  path: '/api/public/office/jwks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMattersSyncRoute = ApiPublicMattersSyncRouteImport.update({
  id: '/api/public/matters/sync',
  path: '/api/public/matters/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntelRunRoute = ApiPublicIntelRunRouteImport.update({
  id: '/api/public/intel/run',
  path: '/api/public/intel/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestIntelRoute = ApiPublicIngestIntelRouteImport.update({
  id: '/api/public/ingest/intel',
  path: '/api/public/ingest/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestBatchesRoute = ApiPublicIngestBatchesRouteImport.update({
  id: '/api/public/ingest/batches',
  path: '/api/public/ingest/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarSyncRoute = ApiPublicCalendarSyncRouteImport.update({
  id: '/api/public/calendar/sync',
  path: '/api/public/calendar/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOfficeSlidesDocIdRoute =
  AuthenticatedOfficeSlidesDocIdRouteImport.update({
    id: '/office/slides/$docId',
    path: '/office/slides/$docId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficeSheetsDocIdRoute =
  AuthenticatedOfficeSheetsDocIdRouteImport.update({
    id: '/office/sheets/$docId',
    path: '/office/sheets/$docId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficeDraftsDraftIdRoute =
  AuthenticatedOfficeDraftsDraftIdRouteImport.update({
    id: '/office/drafts/$draftId',
    path: '/office/drafts/$draftId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiWriterDocsDraftIdRecoveryRoute =
  ApiWriterDocsDraftIdRecoveryRouteImport.update({
    id: '/$draftId/recovery',
    path: '/$draftId/recovery',
    getParentRoute: () => ApiWriterDocsRoute,
  } as any)
const ApiWriterDocsDraftIdContentRoute =
  ApiWriterDocsDraftIdContentRouteImport.update({
    id: '/$draftId/content',
    path: '/$draftId/content',
    getParentRoute: () => ApiWriterDocsRoute,
  } as any)
const ApiPublicIngestBatchesIdRoute =
  ApiPublicIngestBatchesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicIngestBatchesRoute,
  } as any)
const ApiOfficeDocsDocIdRecoveryRoute =
  ApiOfficeDocsDocIdRecoveryRouteImport.update({
    id: '/$docId/recovery',
    path: '/$docId/recovery',
    getParentRoute: () => ApiOfficeDocsRoute,
  } as any)
const ApiOfficeDocsDocIdContentRoute =
  ApiOfficeDocsDocIdContentRouteImport.update({
    id: '/$docId/content',
    path: '/$docId/content',
    getParentRoute: () => ApiOfficeDocsRoute,
  } as any)
const ApiPublicIngestBatchesIdValidateRoute =
  ApiPublicIngestBatchesIdValidateRouteImport.update({
    id: '/validate',
    path: '/validate',
    getParentRoute: () => ApiPublicIngestBatchesIdRoute,
  } as any)
const ApiPublicIngestBatchesIdCommitRoute =
  ApiPublicIngestBatchesIdCommitRouteImport.update({
    id: '/commit',
    path: '/commit',
    getParentRoute: () => ApiPublicIngestBatchesIdRoute,
  } as any)
const ApiPublicOfficeEngineDocsDocIdContentRoute =
  ApiPublicOfficeEngineDocsDocIdContentRouteImport.update({
    id: '/api/public/office/engine/docs/$docId/content',
    path: '/api/public/office/engine/docs/$docId/content',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/eval': typeof AuthenticatedEvalRoute
  '/inspector': typeof AuthenticatedInspectorRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/research': typeof AuthenticatedResearchRoute
  '/summarize': typeof AuthenticatedSummarizeRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/api/followups': typeof ApiFollowupsRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/quick-ask': typeof ApiQuickAskRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/traces': typeof ApiTracesRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/workflows': typeof ApiWorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/archive/courts': typeof AuthenticatedArchiveCourtsRoute
  '/archive/federal': typeof AuthenticatedArchiveFederalRoute
  '/archive/jurisdictions': typeof AuthenticatedArchiveJurisdictionsRoute
  '/drafts/$draftId': typeof AuthenticatedDraftsDraftIdRoute
  '/matters/$slug': typeof AuthenticatedMattersSlugRoute
  '/api/archive/$': typeof ApiArchiveSplatRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/discovery/analyze': typeof ApiDiscoveryAnalyzeRoute
  '/api/kb/ask': typeof ApiKbAskRoute
  '/api/kb/documents': typeof ApiKbDocumentsRoute
  '/api/kb/ingest': typeof ApiKbIngestRoute
  '/api/kb/search': typeof ApiKbSearchRoute
  '/api/office/docs': typeof ApiOfficeDocsRouteWithChildren
  '/api/office/jwks': typeof ApiOfficeJwksRoute
  '/api/office/stream': typeof ApiOfficeStreamRoute
  '/api/pile/ask': typeof ApiPileAskRoute
  '/api/pile/ocr': typeof ApiPileOcrRoute
  '/api/pile/rerank': typeof ApiPileRerankRoute
  '/api/pile/structure': typeof ApiPileStructureRoute
  '/api/review/cell': typeof ApiReviewCellRoute
  '/api/workbench/$': typeof ApiWorkbenchSplatRoute
  '/api/writer/docs': typeof ApiWriterDocsRouteWithChildren
  '/api/writer/stream': typeof ApiWriterStreamRoute
  '/drafts/': typeof AuthenticatedDraftsIndexRoute
  '/matters/': typeof AuthenticatedMattersIndexRoute
  '/office/': typeof AuthenticatedOfficeIndexRoute
  '/office/drafts/$draftId': typeof AuthenticatedOfficeDraftsDraftIdRoute
  '/office/sheets/$docId': typeof AuthenticatedOfficeSheetsDocIdRoute
  '/office/slides/$docId': typeof AuthenticatedOfficeSlidesDocIdRoute
  '/api/public/calendar/sync': typeof ApiPublicCalendarSyncRoute
  '/api/public/ingest/batches': typeof ApiPublicIngestBatchesRouteWithChildren
  '/api/public/ingest/intel': typeof ApiPublicIngestIntelRoute
  '/api/public/intel/run': typeof ApiPublicIntelRunRoute
  '/api/public/matters/sync': typeof ApiPublicMattersSyncRoute
  '/api/public/office/jwks': typeof ApiPublicOfficeJwksRoute
  '/api/public/webhooks/courtlistener': typeof ApiPublicWebhooksCourtlistenerRoute
  '/api/public/webhooks/docketbird': typeof ApiPublicWebhooksDocketbirdRoute
  '/office/drafts/': typeof AuthenticatedOfficeDraftsIndexRoute
  '/office/sheets/': typeof AuthenticatedOfficeSheetsIndexRoute
  '/office/slides/': typeof AuthenticatedOfficeSlidesIndexRoute
  '/api/office/docs/$docId/content': typeof ApiOfficeDocsDocIdContentRoute
  '/api/office/docs/$docId/recovery': typeof ApiOfficeDocsDocIdRecoveryRoute
  '/api/public/ingest/batches/$id': typeof ApiPublicIngestBatchesIdRouteWithChildren
  '/api/writer/docs/$draftId/content': typeof ApiWriterDocsDraftIdContentRoute
  '/api/writer/docs/$draftId/recovery': typeof ApiWriterDocsDraftIdRecoveryRoute
  '/api/public/ingest/batches/$id/commit': typeof ApiPublicIngestBatchesIdCommitRoute
  '/api/public/ingest/batches/$id/validate': typeof ApiPublicIngestBatchesIdValidateRoute
  '/api/public/office/engine/docs/$docId/content': typeof ApiPublicOfficeEngineDocsDocIdContentRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/eval': typeof AuthenticatedEvalRoute
  '/inspector': typeof AuthenticatedInspectorRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/research': typeof AuthenticatedResearchRoute
  '/summarize': typeof AuthenticatedSummarizeRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/api/followups': typeof ApiFollowupsRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/quick-ask': typeof ApiQuickAskRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/traces': typeof ApiTracesRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/workflows': typeof ApiWorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/': typeof AuthenticatedIndexRoute
  '/archive/courts': typeof AuthenticatedArchiveCourtsRoute
  '/archive/federal': typeof AuthenticatedArchiveFederalRoute
  '/archive/jurisdictions': typeof AuthenticatedArchiveJurisdictionsRoute
  '/drafts/$draftId': typeof AuthenticatedDraftsDraftIdRoute
  '/matters/$slug': typeof AuthenticatedMattersSlugRoute
  '/api/archive/$': typeof ApiArchiveSplatRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/discovery/analyze': typeof ApiDiscoveryAnalyzeRoute
  '/api/kb/ask': typeof ApiKbAskRoute
  '/api/kb/documents': typeof ApiKbDocumentsRoute
  '/api/kb/ingest': typeof ApiKbIngestRoute
  '/api/kb/search': typeof ApiKbSearchRoute
  '/api/office/docs': typeof ApiOfficeDocsRouteWithChildren
  '/api/office/jwks': typeof ApiOfficeJwksRoute
  '/api/office/stream': typeof ApiOfficeStreamRoute
  '/api/pile/ask': typeof ApiPileAskRoute
  '/api/pile/ocr': typeof ApiPileOcrRoute
  '/api/pile/rerank': typeof ApiPileRerankRoute
  '/api/pile/structure': typeof ApiPileStructureRoute
  '/api/review/cell': typeof ApiReviewCellRoute
  '/api/workbench/$': typeof ApiWorkbenchSplatRoute
  '/api/writer/docs': typeof ApiWriterDocsRouteWithChildren
  '/api/writer/stream': typeof ApiWriterStreamRoute
  '/drafts': typeof AuthenticatedDraftsIndexRoute
  '/matters': typeof AuthenticatedMattersIndexRoute
  '/office': typeof AuthenticatedOfficeIndexRoute
  '/office/drafts/$draftId': typeof AuthenticatedOfficeDraftsDraftIdRoute
  '/office/sheets/$docId': typeof AuthenticatedOfficeSheetsDocIdRoute
  '/office/slides/$docId': typeof AuthenticatedOfficeSlidesDocIdRoute
  '/api/public/calendar/sync': typeof ApiPublicCalendarSyncRoute
  '/api/public/ingest/batches': typeof ApiPublicIngestBatchesRouteWithChildren
  '/api/public/ingest/intel': typeof ApiPublicIngestIntelRoute
  '/api/public/intel/run': typeof ApiPublicIntelRunRoute
  '/api/public/matters/sync': typeof ApiPublicMattersSyncRoute
  '/api/public/office/jwks': typeof ApiPublicOfficeJwksRoute
  '/api/public/webhooks/courtlistener': typeof ApiPublicWebhooksCourtlistenerRoute
  '/api/public/webhooks/docketbird': typeof ApiPublicWebhooksDocketbirdRoute
  '/office/drafts': typeof AuthenticatedOfficeDraftsIndexRoute
  '/office/sheets': typeof AuthenticatedOfficeSheetsIndexRoute
  '/office/slides': typeof AuthenticatedOfficeSlidesIndexRoute
  '/api/office/docs/$docId/content': typeof ApiOfficeDocsDocIdContentRoute
  '/api/office/docs/$docId/recovery': typeof ApiOfficeDocsDocIdRecoveryRoute
  '/api/public/ingest/batches/$id': typeof ApiPublicIngestBatchesIdRouteWithChildren
  '/api/writer/docs/$draftId/content': typeof ApiWriterDocsDraftIdContentRoute
  '/api/writer/docs/$draftId/recovery': typeof ApiWriterDocsDraftIdRecoveryRoute
  '/api/public/ingest/batches/$id/commit': typeof ApiPublicIngestBatchesIdCommitRoute
  '/api/public/ingest/batches/$id/validate': typeof ApiPublicIngestBatchesIdValidateRoute
  '/api/public/office/engine/docs/$docId/content': typeof ApiPublicOfficeEngineDocsDocIdContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/discovery': typeof AuthenticatedDiscoveryRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/eval': typeof AuthenticatedEvalRoute
  '/_authenticated/inspector': typeof AuthenticatedInspectorRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/summarize': typeof AuthenticatedSummarizeRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/api/followups': typeof ApiFollowupsRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/quick-ask': typeof ApiQuickAskRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/traces': typeof ApiTracesRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/workflows': typeof ApiWorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/archive/courts': typeof AuthenticatedArchiveCourtsRoute
  '/_authenticated/archive/federal': typeof AuthenticatedArchiveFederalRoute
  '/_authenticated/archive/jurisdictions': typeof AuthenticatedArchiveJurisdictionsRoute
  '/_authenticated/drafts/$draftId': typeof AuthenticatedDraftsDraftIdRoute
  '/_authenticated/matters/$slug': typeof AuthenticatedMattersSlugRoute
  '/api/archive/$': typeof ApiArchiveSplatRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/discovery/analyze': typeof ApiDiscoveryAnalyzeRoute
  '/api/kb/ask': typeof ApiKbAskRoute
  '/api/kb/documents': typeof ApiKbDocumentsRoute
  '/api/kb/ingest': typeof ApiKbIngestRoute
  '/api/kb/search': typeof ApiKbSearchRoute
  '/api/office/docs': typeof ApiOfficeDocsRouteWithChildren
  '/api/office/jwks': typeof ApiOfficeJwksRoute
  '/api/office/stream': typeof ApiOfficeStreamRoute
  '/api/pile/ask': typeof ApiPileAskRoute
  '/api/pile/ocr': typeof ApiPileOcrRoute
  '/api/pile/rerank': typeof ApiPileRerankRoute
  '/api/pile/structure': typeof ApiPileStructureRoute
  '/api/review/cell': typeof ApiReviewCellRoute
  '/api/workbench/$': typeof ApiWorkbenchSplatRoute
  '/api/writer/docs': typeof ApiWriterDocsRouteWithChildren
  '/api/writer/stream': typeof ApiWriterStreamRoute
  '/_authenticated/drafts/': typeof AuthenticatedDraftsIndexRoute
  '/_authenticated/matters/': typeof AuthenticatedMattersIndexRoute
  '/_authenticated/office/': typeof AuthenticatedOfficeIndexRoute
  '/_authenticated/office/drafts/$draftId': typeof AuthenticatedOfficeDraftsDraftIdRoute
  '/_authenticated/office/sheets/$docId': typeof AuthenticatedOfficeSheetsDocIdRoute
  '/_authenticated/office/slides/$docId': typeof AuthenticatedOfficeSlidesDocIdRoute
  '/api/public/calendar/sync': typeof ApiPublicCalendarSyncRoute
  '/api/public/ingest/batches': typeof ApiPublicIngestBatchesRouteWithChildren
  '/api/public/ingest/intel': typeof ApiPublicIngestIntelRoute
  '/api/public/intel/run': typeof ApiPublicIntelRunRoute
  '/api/public/matters/sync': typeof ApiPublicMattersSyncRoute
  '/api/public/office/jwks': typeof ApiPublicOfficeJwksRoute
  '/api/public/webhooks/courtlistener': typeof ApiPublicWebhooksCourtlistenerRoute
  '/api/public/webhooks/docketbird': typeof ApiPublicWebhooksDocketbirdRoute
  '/_authenticated/office/drafts/': typeof AuthenticatedOfficeDraftsIndexRoute
  '/_authenticated/office/sheets/': typeof AuthenticatedOfficeSheetsIndexRoute
  '/_authenticated/office/slides/': typeof AuthenticatedOfficeSlidesIndexRoute
  '/api/office/docs/$docId/content': typeof ApiOfficeDocsDocIdContentRoute
  '/api/office/docs/$docId/recovery': typeof ApiOfficeDocsDocIdRecoveryRoute
  '/api/public/ingest/batches/$id': typeof ApiPublicIngestBatchesIdRouteWithChildren
  '/api/writer/docs/$draftId/content': typeof ApiWriterDocsDraftIdContentRoute
  '/api/writer/docs/$draftId/recovery': typeof ApiWriterDocsDraftIdRecoveryRoute
  '/api/public/ingest/batches/$id/commit': typeof ApiPublicIngestBatchesIdCommitRoute
  '/api/public/ingest/batches/$id/validate': typeof ApiPublicIngestBatchesIdValidateRoute
  '/api/public/office/engine/docs/$docId/content': typeof ApiPublicOfficeEngineDocsDocIdContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/conversations'
    | '/discovery'
    | '/docs'
    | '/eval'
    | '/inspector'
    | '/library'
    | '/research'
    | '/summarize'
    | '/workflows'
    | '/api/followups'
    | '/api/orchestrate'
    | '/api/quick-ask'
    | '/api/summarize'
    | '/api/traces'
    | '/api/transcribe'
    | '/api/upload'
    | '/api/workflows'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/archive/courts'
    | '/archive/federal'
    | '/archive/jurisdictions'
    | '/drafts/$draftId'
    | '/matters/$slug'
    | '/api/archive/$'
    | '/api/auth/me'
    | '/api/discovery/analyze'
    | '/api/kb/ask'
    | '/api/kb/documents'
    | '/api/kb/ingest'
    | '/api/kb/search'
    | '/api/office/docs'
    | '/api/office/jwks'
    | '/api/office/stream'
    | '/api/pile/ask'
    | '/api/pile/ocr'
    | '/api/pile/rerank'
    | '/api/pile/structure'
    | '/api/review/cell'
    | '/api/workbench/$'
    | '/api/writer/docs'
    | '/api/writer/stream'
    | '/drafts/'
    | '/matters/'
    | '/office/'
    | '/office/drafts/$draftId'
    | '/office/sheets/$docId'
    | '/office/slides/$docId'
    | '/api/public/calendar/sync'
    | '/api/public/ingest/batches'
    | '/api/public/ingest/intel'
    | '/api/public/intel/run'
    | '/api/public/matters/sync'
    | '/api/public/office/jwks'
    | '/api/public/webhooks/courtlistener'
    | '/api/public/webhooks/docketbird'
    | '/office/drafts/'
    | '/office/sheets/'
    | '/office/slides/'
    | '/api/office/docs/$docId/content'
    | '/api/office/docs/$docId/recovery'
    | '/api/public/ingest/batches/$id'
    | '/api/writer/docs/$draftId/content'
    | '/api/writer/docs/$draftId/recovery'
    | '/api/public/ingest/batches/$id/commit'
    | '/api/public/ingest/batches/$id/validate'
    | '/api/public/office/engine/docs/$docId/content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/calendar'
    | '/conversations'
    | '/discovery'
    | '/docs'
    | '/eval'
    | '/inspector'
    | '/library'
    | '/research'
    | '/summarize'
    | '/workflows'
    | '/api/followups'
    | '/api/orchestrate'
    | '/api/quick-ask'
    | '/api/summarize'
    | '/api/traces'
    | '/api/transcribe'
    | '/api/upload'
    | '/api/workflows'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/'
    | '/archive/courts'
    | '/archive/federal'
    | '/archive/jurisdictions'
    | '/drafts/$draftId'
    | '/matters/$slug'
    | '/api/archive/$'
    | '/api/auth/me'
    | '/api/discovery/analyze'
    | '/api/kb/ask'
    | '/api/kb/documents'
    | '/api/kb/ingest'
    | '/api/kb/search'
    | '/api/office/docs'
    | '/api/office/jwks'
    | '/api/office/stream'
    | '/api/pile/ask'
    | '/api/pile/ocr'
    | '/api/pile/rerank'
    | '/api/pile/structure'
    | '/api/review/cell'
    | '/api/workbench/$'
    | '/api/writer/docs'
    | '/api/writer/stream'
    | '/drafts'
    | '/matters'
    | '/office'
    | '/office/drafts/$draftId'
    | '/office/sheets/$docId'
    | '/office/slides/$docId'
    | '/api/public/calendar/sync'
    | '/api/public/ingest/batches'
    | '/api/public/ingest/intel'
    | '/api/public/intel/run'
    | '/api/public/matters/sync'
    | '/api/public/office/jwks'
    | '/api/public/webhooks/courtlistener'
    | '/api/public/webhooks/docketbird'
    | '/office/drafts'
    | '/office/sheets'
    | '/office/slides'
    | '/api/office/docs/$docId/content'
    | '/api/office/docs/$docId/recovery'
    | '/api/public/ingest/batches/$id'
    | '/api/writer/docs/$draftId/content'
    | '/api/writer/docs/$draftId/recovery'
    | '/api/public/ingest/batches/$id/commit'
    | '/api/public/ingest/batches/$id/validate'
    | '/api/public/office/engine/docs/$docId/content'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/conversations'
    | '/_authenticated/discovery'
    | '/_authenticated/docs'
    | '/_authenticated/eval'
    | '/_authenticated/inspector'
    | '/_authenticated/library'
    | '/_authenticated/research'
    | '/_authenticated/summarize'
    | '/_authenticated/workflows'
    | '/api/followups'
    | '/api/orchestrate'
    | '/api/quick-ask'
    | '/api/summarize'
    | '/api/traces'
    | '/api/transcribe'
    | '/api/upload'
    | '/api/workflows'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/_authenticated/'
    | '/_authenticated/archive/courts'
    | '/_authenticated/archive/federal'
    | '/_authenticated/archive/jurisdictions'
    | '/_authenticated/drafts/$draftId'
    | '/_authenticated/matters/$slug'
    | '/api/archive/$'
    | '/api/auth/me'
    | '/api/discovery/analyze'
    | '/api/kb/ask'
    | '/api/kb/documents'
    | '/api/kb/ingest'
    | '/api/kb/search'
    | '/api/office/docs'
    | '/api/office/jwks'
    | '/api/office/stream'
    | '/api/pile/ask'
    | '/api/pile/ocr'
    | '/api/pile/rerank'
    | '/api/pile/structure'
    | '/api/review/cell'
    | '/api/workbench/$'
    | '/api/writer/docs'
    | '/api/writer/stream'
    | '/_authenticated/drafts/'
    | '/_authenticated/matters/'
    | '/_authenticated/office/'
    | '/_authenticated/office/drafts/$draftId'
    | '/_authenticated/office/sheets/$docId'
    | '/_authenticated/office/slides/$docId'
    | '/api/public/calendar/sync'
    | '/api/public/ingest/batches'
    | '/api/public/ingest/intel'
    | '/api/public/intel/run'
    | '/api/public/matters/sync'
    | '/api/public/office/jwks'
    | '/api/public/webhooks/courtlistener'
    | '/api/public/webhooks/docketbird'
    | '/_authenticated/office/drafts/'
    | '/_authenticated/office/sheets/'
    | '/_authenticated/office/slides/'
    | '/api/office/docs/$docId/content'
    | '/api/office/docs/$docId/recovery'
    | '/api/public/ingest/batches/$id'
    | '/api/writer/docs/$draftId/content'
    | '/api/writer/docs/$draftId/recovery'
    | '/api/public/ingest/batches/$id/commit'
    | '/api/public/ingest/batches/$id/validate'
    | '/api/public/office/engine/docs/$docId/content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiFollowupsRoute: typeof ApiFollowupsRoute
  ApiOrchestrateRoute: typeof ApiOrchestrateRoute
  ApiQuickAskRoute: typeof ApiQuickAskRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
  ApiTracesRoute: typeof ApiTracesRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiWorkflowsRoute: typeof ApiWorkflowsRoute
  ApiArchiveSplatRoute: typeof ApiArchiveSplatRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiDiscoveryAnalyzeRoute: typeof ApiDiscoveryAnalyzeRoute
  ApiKbAskRoute: typeof ApiKbAskRoute
  ApiKbDocumentsRoute: typeof ApiKbDocumentsRoute
  ApiKbIngestRoute: typeof ApiKbIngestRoute
  ApiKbSearchRoute: typeof ApiKbSearchRoute
  ApiOfficeDocsRoute: typeof ApiOfficeDocsRouteWithChildren
  ApiOfficeJwksRoute: typeof ApiOfficeJwksRoute
  ApiOfficeStreamRoute: typeof ApiOfficeStreamRoute
  ApiPileAskRoute: typeof ApiPileAskRoute
  ApiPileOcrRoute: typeof ApiPileOcrRoute
  ApiPileRerankRoute: typeof ApiPileRerankRoute
  ApiPileStructureRoute: typeof ApiPileStructureRoute
  ApiReviewCellRoute: typeof ApiReviewCellRoute
  ApiWorkbenchSplatRoute: typeof ApiWorkbenchSplatRoute
  ApiWriterDocsRoute: typeof ApiWriterDocsRouteWithChildren
  ApiWriterStreamRoute: typeof ApiWriterStreamRoute
  ApiPublicCalendarSyncRoute: typeof ApiPublicCalendarSyncRoute
  ApiPublicIngestBatchesRoute: typeof ApiPublicIngestBatchesRouteWithChildren
  ApiPublicIngestIntelRoute: typeof ApiPublicIngestIntelRoute
  ApiPublicIntelRunRoute: typeof ApiPublicIntelRunRoute
  ApiPublicMattersSyncRoute: typeof ApiPublicMattersSyncRoute
  ApiPublicOfficeJwksRoute: typeof ApiPublicOfficeJwksRoute
  ApiPublicWebhooksCourtlistenerRoute: typeof ApiPublicWebhooksCourtlistenerRoute
  ApiPublicWebhooksDocketbirdRoute: typeof ApiPublicWebhooksDocketbirdRoute
  ApiPublicOfficeEngineDocsDocIdContentRoute: typeof ApiPublicOfficeEngineDocsDocIdContentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/workflows': {
      id: '/api/workflows'
      path: '/api/workflows'
      fullPath: '/api/workflows'
      preLoaderRoute: typeof ApiWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traces': {
      id: '/api/traces'
      path: '/api/traces'
      fullPath: '/api/traces'
      preLoaderRoute: typeof ApiTracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quick-ask': {
      id: '/api/quick-ask'
      path: '/api/quick-ask'
      fullPath: '/api/quick-ask'
      preLoaderRoute: typeof ApiQuickAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orchestrate': {
      id: '/api/orchestrate'
      path: '/api/orchestrate'
      fullPath: '/api/orchestrate'
      preLoaderRoute: typeof ApiOrchestrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/followups': {
      id: '/api/followups'
      path: '/api/followups'
      fullPath: '/api/followups'
      preLoaderRoute: typeof ApiFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/summarize': {
      id: '/_authenticated/summarize'
      path: '/summarize'
      fullPath: '/summarize'
      preLoaderRoute: typeof AuthenticatedSummarizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspector': {
      id: '/_authenticated/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof AuthenticatedInspectorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eval': {
      id: '/_authenticated/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof AuthenticatedEvalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discovery': {
      id: '/_authenticated/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office/': {
      id: '/_authenticated/office/'
      path: '/office'
      fullPath: '/office/'
      preLoaderRoute: typeof AuthenticatedOfficeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matters/': {
      id: '/_authenticated/matters/'
      path: '/matters'
      fullPath: '/matters/'
      preLoaderRoute: typeof AuthenticatedMattersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts/': {
      id: '/_authenticated/drafts/'
      path: '/drafts'
      fullPath: '/drafts/'
      preLoaderRoute: typeof AuthenticatedDraftsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/writer/stream': {
      id: '/api/writer/stream'
      path: '/api/writer/stream'
      fullPath: '/api/writer/stream'
      preLoaderRoute: typeof ApiWriterStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/writer/docs': {
      id: '/api/writer/docs'
      path: '/api/writer/docs'
      fullPath: '/api/writer/docs'
      preLoaderRoute: typeof ApiWriterDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workbench/$': {
      id: '/api/workbench/$'
      path: '/api/workbench/$'
      fullPath: '/api/workbench/$'
      preLoaderRoute: typeof ApiWorkbenchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/cell': {
      id: '/api/review/cell'
      path: '/api/review/cell'
      fullPath: '/api/review/cell'
      preLoaderRoute: typeof ApiReviewCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pile/structure': {
      id: '/api/pile/structure'
      path: '/api/pile/structure'
      fullPath: '/api/pile/structure'
      preLoaderRoute: typeof ApiPileStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pile/rerank': {
      id: '/api/pile/rerank'
      path: '/api/pile/rerank'
      fullPath: '/api/pile/rerank'
      preLoaderRoute: typeof ApiPileRerankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pile/ocr': {
      id: '/api/pile/ocr'
      path: '/api/pile/ocr'
      fullPath: '/api/pile/ocr'
      preLoaderRoute: typeof ApiPileOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pile/ask': {
      id: '/api/pile/ask'
      path: '/api/pile/ask'
      fullPath: '/api/pile/ask'
      preLoaderRoute: typeof ApiPileAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/office/stream': {
      id: '/api/office/stream'
      path: '/api/office/stream'
      fullPath: '/api/office/stream'
      preLoaderRoute: typeof ApiOfficeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/office/jwks': {
      id: '/api/office/jwks'
      path: '/api/office/jwks'
      fullPath: '/api/office/jwks'
      preLoaderRoute: typeof ApiOfficeJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/office/docs': {
      id: '/api/office/docs'
      path: '/api/office/docs'
      fullPath: '/api/office/docs'
      preLoaderRoute: typeof ApiOfficeDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kb/search': {
      id: '/api/kb/search'
      path: '/api/kb/search'
      fullPath: '/api/kb/search'
      preLoaderRoute: typeof ApiKbSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kb/ingest': {
      id: '/api/kb/ingest'
      path: '/api/kb/ingest'
      fullPath: '/api/kb/ingest'
      preLoaderRoute: typeof ApiKbIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kb/documents': {
      id: '/api/kb/documents'
      path: '/api/kb/documents'
      fullPath: '/api/kb/documents'
      preLoaderRoute: typeof ApiKbDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kb/ask': {
      id: '/api/kb/ask'
      path: '/api/kb/ask'
      fullPath: '/api/kb/ask'
      preLoaderRoute: typeof ApiKbAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/analyze': {
      id: '/api/discovery/analyze'
      path: '/api/discovery/analyze'
      fullPath: '/api/discovery/analyze'
      preLoaderRoute: typeof ApiDiscoveryAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive/$': {
      id: '/api/archive/$'
      path: '/api/archive/$'
      fullPath: '/api/archive/$'
      preLoaderRoute: typeof ApiArchiveSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/matters/$slug': {
      id: '/_authenticated/matters/$slug'
      path: '/matters/$slug'
      fullPath: '/matters/$slug'
      preLoaderRoute: typeof AuthenticatedMattersSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts/$draftId': {
      id: '/_authenticated/drafts/$draftId'
      path: '/drafts/$draftId'
      fullPath: '/drafts/$draftId'
      preLoaderRoute: typeof AuthenticatedDraftsDraftIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/jurisdictions': {
      id: '/_authenticated/archive/jurisdictions'
      path: '/archive/jurisdictions'
      fullPath: '/archive/jurisdictions'
      preLoaderRoute: typeof AuthenticatedArchiveJurisdictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/federal': {
      id: '/_authenticated/archive/federal'
      path: '/archive/federal'
      fullPath: '/archive/federal'
      preLoaderRoute: typeof AuthenticatedArchiveFederalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/courts': {
      id: '/_authenticated/archive/courts'
      path: '/archive/courts'
      fullPath: '/archive/courts'
      preLoaderRoute: typeof AuthenticatedArchiveCourtsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office/slides/': {
      id: '/_authenticated/office/slides/'
      path: '/office/slides'
      fullPath: '/office/slides/'
      preLoaderRoute: typeof AuthenticatedOfficeSlidesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office/sheets/': {
      id: '/_authenticated/office/sheets/'
      path: '/office/sheets'
      fullPath: '/office/sheets/'
      preLoaderRoute: typeof AuthenticatedOfficeSheetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office/drafts/': {
      id: '/_authenticated/office/drafts/'
      path: '/office/drafts'
      fullPath: '/office/drafts/'
      preLoaderRoute: typeof AuthenticatedOfficeDraftsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/docketbird': {
      id: '/api/public/webhooks/docketbird'
      path: '/api/public/webhooks/docketbird'
      fullPath: '/api/public/webhooks/docketbird'
      preLoaderRoute: typeof ApiPublicWebhooksDocketbirdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/courtlistener': {
      id: '/api/public/webhooks/courtlistener'
      path: '/api/public/webhooks/courtlistener'
      fullPath: '/api/public/webhooks/courtlistener'
      preLoaderRoute: typeof ApiPublicWebhooksCourtlistenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/office/jwks': {
      id: '/api/public/office/jwks'
      path: '/api/public/office/jwks'
      fullPath: '/api/public/office/jwks'
      preLoaderRoute: typeof ApiPublicOfficeJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/matters/sync': {
      id: '/api/public/matters/sync'
      path: '/api/public/matters/sync'
      fullPath: '/api/public/matters/sync'
      preLoaderRoute: typeof ApiPublicMattersSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/intel/run': {
      id: '/api/public/intel/run'
      path: '/api/public/intel/run'
      fullPath: '/api/public/intel/run'
      preLoaderRoute: typeof ApiPublicIntelRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/intel': {
      id: '/api/public/ingest/intel'
      path: '/api/public/ingest/intel'
      fullPath: '/api/public/ingest/intel'
      preLoaderRoute: typeof ApiPublicIngestIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/batches': {
      id: '/api/public/ingest/batches'
      path: '/api/public/ingest/batches'
      fullPath: '/api/public/ingest/batches'
      preLoaderRoute: typeof ApiPublicIngestBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/sync': {
      id: '/api/public/calendar/sync'
      path: '/api/public/calendar/sync'
      fullPath: '/api/public/calendar/sync'
      preLoaderRoute: typeof ApiPublicCalendarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/office/slides/$docId': {
      id: '/_authenticated/office/slides/$docId'
      path: '/office/slides/$docId'
      fullPath: '/office/slides/$docId'
      preLoaderRoute: typeof AuthenticatedOfficeSlidesDocIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office/sheets/$docId': {
      id: '/_authenticated/office/sheets/$docId'
      path: '/office/sheets/$docId'
      fullPath: '/office/sheets/$docId'
      preLoaderRoute: typeof AuthenticatedOfficeSheetsDocIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office/drafts/$draftId': {
      id: '/_authenticated/office/drafts/$draftId'
      path: '/office/drafts/$draftId'
      fullPath: '/office/drafts/$draftId'
      preLoaderRoute: typeof AuthenticatedOfficeDraftsDraftIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/writer/docs/$draftId/recovery': {
      id: '/api/writer/docs/$draftId/recovery'
      path: '/$draftId/recovery'
      fullPath: '/api/writer/docs/$draftId/recovery'
      preLoaderRoute: typeof ApiWriterDocsDraftIdRecoveryRouteImport
      parentRoute: typeof ApiWriterDocsRoute
    }
    '/api/writer/docs/$draftId/content': {
      id: '/api/writer/docs/$draftId/content'
      path: '/$draftId/content'
      fullPath: '/api/writer/docs/$draftId/content'
      preLoaderRoute: typeof ApiWriterDocsDraftIdContentRouteImport
      parentRoute: typeof ApiWriterDocsRoute
    }
    '/api/public/ingest/batches/$id': {
      id: '/api/public/ingest/batches/$id'
      path: '/$id'
      fullPath: '/api/public/ingest/batches/$id'
      preLoaderRoute: typeof ApiPublicIngestBatchesIdRouteImport
      parentRoute: typeof ApiPublicIngestBatchesRoute
    }
    '/api/office/docs/$docId/recovery': {
      id: '/api/office/docs/$docId/recovery'
      path: '/$docId/recovery'
      fullPath: '/api/office/docs/$docId/recovery'
      preLoaderRoute: typeof ApiOfficeDocsDocIdRecoveryRouteImport
      parentRoute: typeof ApiOfficeDocsRoute
    }
    '/api/office/docs/$docId/content': {
      id: '/api/office/docs/$docId/content'
      path: '/$docId/content'
      fullPath: '/api/office/docs/$docId/content'
      preLoaderRoute: typeof ApiOfficeDocsDocIdContentRouteImport
      parentRoute: typeof ApiOfficeDocsRoute
    }
    '/api/public/ingest/batches/$id/validate': {
      id: '/api/public/ingest/batches/$id/validate'
      path: '/validate'
      fullPath: '/api/public/ingest/batches/$id/validate'
      preLoaderRoute: typeof ApiPublicIngestBatchesIdValidateRouteImport
      parentRoute: typeof ApiPublicIngestBatchesIdRoute
    }
    '/api/public/ingest/batches/$id/commit': {
      id: '/api/public/ingest/batches/$id/commit'
      path: '/commit'
      fullPath: '/api/public/ingest/batches/$id/commit'
      preLoaderRoute: typeof ApiPublicIngestBatchesIdCommitRouteImport
      parentRoute: typeof ApiPublicIngestBatchesIdRoute
    }
    '/api/public/office/engine/docs/$docId/content': {
      id: '/api/public/office/engine/docs/$docId/content'
      path: '/api/public/office/engine/docs/$docId/content'
      fullPath: '/api/public/office/engine/docs/$docId/content'
      preLoaderRoute: typeof ApiPublicOfficeEngineDocsDocIdContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDiscoveryRoute: typeof AuthenticatedDiscoveryRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedEvalRoute: typeof AuthenticatedEvalRoute
  AuthenticatedInspectorRoute: typeof AuthenticatedInspectorRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedSummarizeRoute: typeof AuthenticatedSummarizeRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedArchiveCourtsRoute: typeof AuthenticatedArchiveCourtsRoute
  AuthenticatedArchiveFederalRoute: typeof AuthenticatedArchiveFederalRoute
  AuthenticatedArchiveJurisdictionsRoute: typeof AuthenticatedArchiveJurisdictionsRoute
  AuthenticatedDraftsDraftIdRoute: typeof AuthenticatedDraftsDraftIdRoute
  AuthenticatedMattersSlugRoute: typeof AuthenticatedMattersSlugRoute
  AuthenticatedDraftsIndexRoute: typeof AuthenticatedDraftsIndexRoute
  AuthenticatedMattersIndexRoute: typeof AuthenticatedMattersIndexRoute
  AuthenticatedOfficeIndexRoute: typeof AuthenticatedOfficeIndexRoute
  AuthenticatedOfficeDraftsDraftIdRoute: typeof AuthenticatedOfficeDraftsDraftIdRoute
  AuthenticatedOfficeSheetsDocIdRoute: typeof AuthenticatedOfficeSheetsDocIdRoute
  AuthenticatedOfficeSlidesDocIdRoute: typeof AuthenticatedOfficeSlidesDocIdRoute
  AuthenticatedOfficeDraftsIndexRoute: typeof AuthenticatedOfficeDraftsIndexRoute
  AuthenticatedOfficeSheetsIndexRoute: typeof AuthenticatedOfficeSheetsIndexRoute
  AuthenticatedOfficeSlidesIndexRoute: typeof AuthenticatedOfficeSlidesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDiscoveryRoute: AuthenticatedDiscoveryRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedEvalRoute: AuthenticatedEvalRoute,
  AuthenticatedInspectorRoute: AuthenticatedInspectorRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedSummarizeRoute: AuthenticatedSummarizeRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedArchiveCourtsRoute: AuthenticatedArchiveCourtsRoute,
  AuthenticatedArchiveFederalRoute: AuthenticatedArchiveFederalRoute,
  AuthenticatedArchiveJurisdictionsRoute:
    AuthenticatedArchiveJurisdictionsRoute,
  AuthenticatedDraftsDraftIdRoute: AuthenticatedDraftsDraftIdRoute,
  AuthenticatedMattersSlugRoute: AuthenticatedMattersSlugRoute,
  AuthenticatedDraftsIndexRoute: AuthenticatedDraftsIndexRoute,
  AuthenticatedMattersIndexRoute: AuthenticatedMattersIndexRoute,
  AuthenticatedOfficeIndexRoute: AuthenticatedOfficeIndexRoute,
  AuthenticatedOfficeDraftsDraftIdRoute: AuthenticatedOfficeDraftsDraftIdRoute,
  AuthenticatedOfficeSheetsDocIdRoute: AuthenticatedOfficeSheetsDocIdRoute,
  AuthenticatedOfficeSlidesDocIdRoute: AuthenticatedOfficeSlidesDocIdRoute,
  AuthenticatedOfficeDraftsIndexRoute: AuthenticatedOfficeDraftsIndexRoute,
  AuthenticatedOfficeSheetsIndexRoute: AuthenticatedOfficeSheetsIndexRoute,
  AuthenticatedOfficeSlidesIndexRoute: AuthenticatedOfficeSlidesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiOfficeDocsRouteChildren {
  ApiOfficeDocsDocIdContentRoute: typeof ApiOfficeDocsDocIdContentRoute
  ApiOfficeDocsDocIdRecoveryRoute: typeof ApiOfficeDocsDocIdRecoveryRoute
}

const ApiOfficeDocsRouteChildren: ApiOfficeDocsRouteChildren = {
  ApiOfficeDocsDocIdContentRoute: ApiOfficeDocsDocIdContentRoute,
  ApiOfficeDocsDocIdRecoveryRoute: ApiOfficeDocsDocIdRecoveryRoute,
}

const ApiOfficeDocsRouteWithChildren = ApiOfficeDocsRoute._addFileChildren(
  ApiOfficeDocsRouteChildren,
)

interface ApiWriterDocsRouteChildren {
  ApiWriterDocsDraftIdContentRoute: typeof ApiWriterDocsDraftIdContentRoute
  ApiWriterDocsDraftIdRecoveryRoute: typeof ApiWriterDocsDraftIdRecoveryRoute
}

const ApiWriterDocsRouteChildren: ApiWriterDocsRouteChildren = {
  ApiWriterDocsDraftIdContentRoute: ApiWriterDocsDraftIdContentRoute,
  ApiWriterDocsDraftIdRecoveryRoute: ApiWriterDocsDraftIdRecoveryRoute,
}

const ApiWriterDocsRouteWithChildren = ApiWriterDocsRoute._addFileChildren(
  ApiWriterDocsRouteChildren,
)

interface ApiPublicIngestBatchesIdRouteChildren {
  ApiPublicIngestBatchesIdCommitRoute: typeof ApiPublicIngestBatchesIdCommitRoute
  ApiPublicIngestBatchesIdValidateRoute: typeof ApiPublicIngestBatchesIdValidateRoute
}

const ApiPublicIngestBatchesIdRouteChildren: ApiPublicIngestBatchesIdRouteChildren =
  {
    ApiPublicIngestBatchesIdCommitRoute: ApiPublicIngestBatchesIdCommitRoute,
    ApiPublicIngestBatchesIdValidateRoute:
      ApiPublicIngestBatchesIdValidateRoute,
  }

const ApiPublicIngestBatchesIdRouteWithChildren =
  ApiPublicIngestBatchesIdRoute._addFileChildren(
    ApiPublicIngestBatchesIdRouteChildren,
  )

interface ApiPublicIngestBatchesRouteChildren {
  ApiPublicIngestBatchesIdRoute: typeof ApiPublicIngestBatchesIdRouteWithChildren
}

const ApiPublicIngestBatchesRouteChildren: ApiPublicIngestBatchesRouteChildren =
  {
    ApiPublicIngestBatchesIdRoute: ApiPublicIngestBatchesIdRouteWithChildren,
  }

const ApiPublicIngestBatchesRouteWithChildren =
  ApiPublicIngestBatchesRoute._addFileChildren(
    ApiPublicIngestBatchesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiFollowupsRoute: ApiFollowupsRoute,
  ApiOrchestrateRoute: ApiOrchestrateRoute,
  ApiQuickAskRoute: ApiQuickAskRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
  ApiTracesRoute: ApiTracesRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiWorkflowsRoute: ApiWorkflowsRoute,
  ApiArchiveSplatRoute: ApiArchiveSplatRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiDiscoveryAnalyzeRoute: ApiDiscoveryAnalyzeRoute,
  ApiKbAskRoute: ApiKbAskRoute,
  ApiKbDocumentsRoute: ApiKbDocumentsRoute,
  ApiKbIngestRoute: ApiKbIngestRoute,
  ApiKbSearchRoute: ApiKbSearchRoute,
  ApiOfficeDocsRoute: ApiOfficeDocsRouteWithChildren,
  ApiOfficeJwksRoute: ApiOfficeJwksRoute,
  ApiOfficeStreamRoute: ApiOfficeStreamRoute,
  ApiPileAskRoute: ApiPileAskRoute,
  ApiPileOcrRoute: ApiPileOcrRoute,
  ApiPileRerankRoute: ApiPileRerankRoute,
  ApiPileStructureRoute: ApiPileStructureRoute,
  ApiReviewCellRoute: ApiReviewCellRoute,
  ApiWorkbenchSplatRoute: ApiWorkbenchSplatRoute,
  ApiWriterDocsRoute: ApiWriterDocsRouteWithChildren,
  ApiWriterStreamRoute: ApiWriterStreamRoute,
  ApiPublicCalendarSyncRoute: ApiPublicCalendarSyncRoute,
  ApiPublicIngestBatchesRoute: ApiPublicIngestBatchesRouteWithChildren,
  ApiPublicIngestIntelRoute: ApiPublicIngestIntelRoute,
  ApiPublicIntelRunRoute: ApiPublicIntelRunRoute,
  ApiPublicMattersSyncRoute: ApiPublicMattersSyncRoute,
  ApiPublicOfficeJwksRoute: ApiPublicOfficeJwksRoute,
  ApiPublicWebhooksCourtlistenerRoute: ApiPublicWebhooksCourtlistenerRoute,
  ApiPublicWebhooksDocketbirdRoute: ApiPublicWebhooksDocketbirdRoute,
  ApiPublicOfficeEngineDocsDocIdContentRoute:
    ApiPublicOfficeEngineDocsDocIdContentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
